Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-08, with the labels that each got.

#772 Added unit test for DepartmentController
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentControllerTest.java
Labels: status: ready-for-review

#777 Added unit test for BaseController.
  src/test/java/org/synyx/urlaubsverwaltung/overview/BaseControllerTest.java
Labels: status: ready-for-review

#779 Added unit test for ApplicationForLeaveForm.
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
Labels: status: ready-for-review

#773 Added unit test for ApplicationForLeaveStatisticsController
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsControllerTest.java
Labels: status: ready-for-review

#774 Extended unit test for AvailabilityController
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityControllerTest.java
Labels: status: ready-for-review

#780 Extended unit test for AccountForm.
  src/test/java/org/synyx/urlaubsverwaltung/account/web/AccountFormTest.java
Labels: status: ready-for-review

#776 Extend unit test ApplyForLeaveController to cover missing execution path
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveControllerTest.java
Labels: status: ready-for-review

#775 Extended unit test for OvertimeController
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeControllerTest.java
Labels: status: ready-for-review

#778 Added unit test for DepartmentResponse.
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponseTest.java
Labels: status: ready-for-review

#781 Added unit test for PersonPropertyEditor.
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPropertyEditorTest.java
Labels: status: ready-for-review

#771 Remove heroku app.json
  app.json
Labels: status: ready-for-review

#770 Remove heroku procfile
  Procfile
Labels: status: ready-for-review

#782 Upgrade spring boot parent to 2.1.7
  CHANGELOG.md
  pom.xml
Labels: status: ready-for-review

#789 Replace assert with assertj
  src/test/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/web/AccountValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/api/ErrorResponseTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/UnknownPersonExceptionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/SickDaysTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/UsedDaysOverviewTest.java
Labels: status: ready-for-review

#759 Decouple auth from api
  CHANGELOG.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonResponseMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponseTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerTest.java
Labels: status: waiting-for-reply

#793 Remove users.ldif in production code.
  src/main/resources/users.ldif
Labels: status: ready-for-review

#794 Reduce logging on build
  src/test/resources/application.properties
  src/test/resources/logback-test.xml
Labels: status: ready-for-review

#795 Remove liquibase context from properties
  src/main/resources/application.properties
Labels: status: ready-for-review

#792 Use GitHub Action to build the application
  .github/workflows/maven.yml
  travis.yml
Labels: status: work-in-progress

#798 Move from probot to stale action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: status: ready-for-review

#799 Enable travis build again
  .travis.yml
Labels: status: ready-for-review
