Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-04, with the labels that each got.

#602 Fix errors/warning in build
  package.json
  pom.xml
Labels: status: work-in-progress

#603 Upgrade bootstrap to 3.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: status: ready-for-review

#606 Remove print() in integration test
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceControllerTest.java
Labels: status: ready-for-review

#608 add eslint-plugin-urlaubsverwaltung to enforce custom javascript rules
  .eslintrc
  .gitignore
  eslint-plugin-urlaubsverwaltung/README.md
  eslint-plugin-urlaubsverwaltung/index.js
  eslint-plugin-urlaubsverwaltung/package-lock.json
  eslint-plugin-urlaubsverwaltung/package.json
  eslint-plugin-urlaubsverwaltung/rules/no-date-fns.js
  eslint-plugin-urlaubsverwaltung/test/no-date-fns.spec.js
  package-lock.json
  package.json
  src/main/webapp/lib/date-fns/locale-resolver.js
Labels: status: ready-for-review

#604 Exhange calendar delete discovery directory logging
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProvider.java
Labels: status: ready-for-review

#614 Upgrade spring boot to 2.1.4
  CHANGELOG.md
  pom.xml
Labels: status: ready-for-review

#619 Remove deprecated and unused code
  src/main/java/org/synyx/urlaubsverwaltung/account/service/VacationDaysService.java
Labels: status: ready-for-review

#620 Improve Model: AbsenseResponse
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteResponse.java
Labels: status: ready-for-review

#609 No autocomplete on email delivery settings username/password
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
Labels: status: ready-for-review

#629 Add toString to VacationDaysLeft
  src/main/java/org/synyx/urlaubsverwaltung/account/domain/VacationDaysLeft.java
Labels: status: ready-for-review

#628 Add missing ftm import in overview
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
Labels: status: ready-for-review

#631 Fix to use correct java 8 DateTimeFormatter
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProvider.java
Labels: status: ready-for-review

#635 Default constructor of SickNoteConvertForm needs to be public...
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteConvertForm.java
Labels: status: ready-for-review

#639 Fix jquery ui themes import
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: ready-for-review

#641 Fix datepicker for sicknotes
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/bundles/sick-note-form.js
  src/main/webapp/js/sick-notes/sick-note-form.js
Labels: status: ready-for-review

#642 Fix datepicker for overtime
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/bundles/overtime-form.js
  src/main/webapp/js/overtime/overtime-form.js
Labels: status: ready-for-review

#644 Fix autocompletion for sick note datepicker
  CHANGELOG.md
  src/main/webapp/js/sick-notes/sick-note-form.js
Labels: status: ready-for-review

#646 Upgrade maven version to 3.6.1
  .mvn/wrapper/maven-wrapper.properties
Labels: status: ready-for-review

#648 adding count and maxChars in app-form.js
  CHANGELOG.md
  src/main/webapp/bundles/account-form.js
  src/main/webapp/bundles/app-detail.js
  src/main/webapp/bundles/app-form.js
  src/main/webapp/bundles/overtime-form.js
Labels: status: ready-for-review

#650 Fix maximum sick pay days
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/sicknote_end_of_sick_pay.ftl
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplIT.java
Labels: status: ready-for-review

#655 delete eslint-plugin-urlaubsverwaltung and use the new published arti…
  .eslintrc
  eslint-plugin-urlaubsverwaltung/README.md
  eslint-plugin-urlaubsverwaltung/index.js
  eslint-plugin-urlaubsverwaltung/package-lock.json
  eslint-plugin-urlaubsverwaltung/package.json
  eslint-plugin-urlaubsverwaltung/rules/no-date-fns.js
  eslint-plugin-urlaubsverwaltung/test/no-date-fns.spec.js
  package-lock.json
  package.json
Labels: status: ready-for-review

#656 Replace … with ...
  src/main/resources/messages_en.properties
Labels: status: ready-for-review

#652 Allow half day input on account form for remaining vacation days
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/account/web/AccountForm.java
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/tags/input-number.tag
Labels: status: ready-for-review

#651 Fix workdays and vacations api usage
  package-lock.json
  package.json
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsController.java
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/bundles/person-overview.js
  src/main/webapp/js/__tests__/fetch.spec.js
  src/main/webapp/js/fetch.js
  src/main/webapp/js/person/overview-app-list.js
  src/main/webapp/js/send-get-days-request-for-turn-of-the-year.js
  src/main/webapp/js/send-get-days-request.js
  src/main/webapp/js/send-get-department-vacations-request.js
Labels: status: ready-for-review

#658 JavaScript coverage
  .travis.yml
  package.json
  pom.xml
Labels: status: ready-for-review

#662 Fix creation of admin user for testdata
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestDataCreationService.java
Labels: status: ready-for-review

#670 Bug/overlapping temporaryallowed
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/OverlapService.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/OverlapServiceTest.java
Labels: status: ready-for-review

#657 show approvable applications for departmentHead and secondStageAuth
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/staff/web/StaffController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: ready-for-review

#674 Fix character counter in overtime form
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
Labels: status: ready-for-review

#671 Bug/fix translations
  CHANGELOG.md
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/js/send-get-days-request.js
  src/main/webapp/js/send-get-department-vacations-request.js
Labels: status: ready-for-review

#675 calendar settings not configurable for google and exchange
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/js/settings/settings-form.js
Labels: status: ready-for-review

#663 second stage auth does not have to be in the department
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentValidatorTest.java
Labels: status: ready-for-review

#633 Show morning, noon and full absence in calendar
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/DayAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/DayAbsenceList.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayController.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/PublicHolidaysService.java
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/components/calendar/__snapshots__/calendar.spec.js.snap
  src/main/webapp/components/calendar/calendar.css
  src/main/webapp/components/calendar/calendar.spec.js
  src/main/webapp/components/calendar/index.js
  src/main/webapp/components/datepicker/create-datepicker-instances.js
  src/main/webapp/components/datepicker/datepicker.css
  src/main/webapp/css/vacation-overview.css
  src/main/webapp/js/__tests__/__snapshots__/html-literal.spec.js.snap
  src/main/webapp/js/__tests__/html-literal.spec.js
  src/main/webapp/js/html-literal.js
  src/main/webapp/js/vacation-overview.js
  src/test/java/org/synyx/urlaubsverwaltung/account/service/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/PublicHolidaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysServiceTest.java
Labels: status: needs-work

#668 Annual vacation settings steps to 0.5
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
Labels: status: ready-for-review
