Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-07, with the labels that each got.

#721 Javascript linting
  package-lock.json
  package.json
  pom.xml
  src/main/webapp/js/fetch.js
  src/main/webapp/js/html-literal.js
Labels: status: ready-for-review

#722 Bugfix/holiday christmas newyear
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationValidatorTest.java
Labels: status: ready-for-review

#636 a comment can be added while creating new sick-note
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteForm.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/bundles/sick-note-form.js
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteFormTest.java
Labels: status: ready-for-review

#709 sickNoteId is never the sickNotePersonId but that should be returned
  CHANGELOG.md
  src/main/webapp/components/datepicker/create-datepicker-instances.js
  src/main/webapp/js/sick-notes/sick-note-form.js
Labels: status: ready-for-review

#725 Fix some sonar issues
  src/main/java/org/synyx/urlaubsverwaltung/account/service/TurnOfTheYearAccountUpdaterService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/ApplicationForLeaveDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCronMailService.java
  src/test/java/org/synyx/urlaubsverwaltung/account/service/TurnOfTheYearAccountUpdaterServiceTest.java
Labels: status: ready-for-review

#727 fix minor errors and slightly restructure project documentation in README
  README.md
Labels: type: enhancement

#732 Add new banner
  src/main/resources/banner.txt
Labels: status: ready-for-review

#731 fix api result for user without active workingtime
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/api/ApiExceptionHandlerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceException.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/NoValidWorkingTimeException.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayControllerTest.java
Labels: status: ready-for-review

#733 fix api result for user without active workingtime
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/api/ApiExceptionHandlerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceException.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/NoValidWorkingTimeException.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayControllerTest.java
Labels: status: ready-for-review, topic: api, type: bug

#716 New Security Provider with OpenId Connect (oidc)
  .examples/docker-compose/with-mariadb/application.properties
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/PersonSyncService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SecurityConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/ActiveDirectorySecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/ActiveDirectorySecurityConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/DirectoryServiceSecurityProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapSecurityConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUser.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandler.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonMappingException.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
  src/main/resources/application-testdata.properties
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/tags/person.tag
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/PersonSyncServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandlerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
Labels: status: ready-for-review

#738 Cleanup/fix some sonar issues
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProvider.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpansTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
Labels: status: ready-for-review

#739 Cleanup/some sonar bugs
  src/main/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysService.java
  src/test/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionServiceImplTest.java
Labels: status: ready-for-review

#741 permit request to favicon.ico for everyone
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
Labels: status: ready-for-review

#740 Fix corrupt docker container
  Dockerfile
  pom.xml
Labels: status: ready-for-review

#742 Add demo system part in the readme
  README.md
  src/main/webapp/WEB-INF/jsp/login/login.jsp
Labels: status: ready-for-review

#744 Add overtime controller tests
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeController.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeControllerTest.java
Labels: status: ready-for-review

#751 Fix to highlight current day in vacation request
  CHANGELOG.md
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/components/datepicker/create-datepicker-instances.js
Labels: status: ready-for-review

#753 Added unit test for PersonManagementController
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementControllerTest.java
Labels: status: ready-for-review

#752 Added unit test for web.PersonController
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonControllerTest.java
Labels: status: ready-for-review

#757 remove legacy docs
  docs/LEGACY_WAR_INSTALLATION.md
  docs/UV_WITH_DOCKER.md
  docs/heroku.md
  docs/uv-02.png
Labels: status: ready-for-review

#758 Extended SickNoteControllerTest
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteControllerTest.java
Labels: status: ready-for-review

#756 Extended SettingsControllerTest
  src/test/java/org/synyx/urlaubsverwaltung/settings/web/SettingsControllerTest.java
Labels: status: ready-for-review

#761 Activate method security for @Pre and @PostAuthorize
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewControllerSecurityIT.java
Labels: status: ready-for-review, topic: security

#764 Add ErrorController Tests
  src/test/java/org/synyx/urlaubsverwaltung/web/ErrorControllerTest.java
Labels: status: ready-for-review

#763 Add prerelease=true to release for gitHub until 3.0 final release
  .travis.yml
Labels: status: ready-for-review

#762 Added unit test for WorkingTimeController.
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/web/WorkingTimeForm.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/web/WorkingTimeControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/web/WorkingTimeFormTest.java
Labels: status: ready-for-review

#767 Added unit test for AccountController
  src/test/java/org/synyx/urlaubsverwaltung/account/web/AccountControllerTest.java
Labels: status: ready-for-review

#766 Added unit test for LoginController
  src/test/java/org/synyx/urlaubsverwaltung/security/LoginControllerTest.java
Labels: status: ready-for-review

#769 Extended unit test of ApplyForLeaveControllerTest.
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveControllerTest.java
Labels: status: ready-for-review

#768 Added unit test for ApplicationForLeaveDetailsController.
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsControllerTest.java
Labels: status: ready-for-review
