Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-12, with the labels that each got.

#896 Add further html titles
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: planned, status: work-in-progress

#897 Do not bound controller by global constants
  src/main/java/org/synyx/urlaubsverwaltung/account/web/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/web/GoogleCalendarOAuthHandshakeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/web/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/ControllerConstants.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/web/SettingsViewControllerTest.java
Labels: status: planned, status: ready-for-review

#900 Upgrade spring boot to 2.1.11
  CHANGELOG.md
  pom.xml
Labels: dependencies, status: planned, status: ready-for-review

#881 Prepare deployment for 3.0.0
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/requirements.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/values-existing-mariadb.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/values-mariadb.yaml
  .examples/kubernetes/yaml/urlaubsverwaltung.yml
Labels: status: planned, status: ready-for-review

#902 Remove 'comment' from account...
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/account/domain/Account.java
  src/test/java/org/synyx/urlaubsverwaltung/account/domain/AccountTest.java
Labels: status: planned, status: ready-for-review

#901 Remove 'reason' from application logging...
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/Application.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
Labels: status: planned, status: ready-for-review

#905 Add admin roles message property
  CHANGELOG.md
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#909 Rename to ApplicationForLeaveFormValidator
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveViewControllerTest.java
Labels: status: planned

#910 Rename to ApplicationForLeaveFormViewController
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned

#912 Remove 'reason' and 'comment' from ApplicationForLeaveForm logging...
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
Labels: status: planned, status: ready-for-review

#913 Remove 'comment' from SickNoteForm logging...
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteForm.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteFormTest.java
Labels: status: planned

#908 use v1 release in github actions to have latest
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: status: planned, status: ready-for-review

#914 Fix ldap and ad sync can not be enabled
  CHANGELOG.md
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/ActiveDirectorySecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapSecurityConfiguration.java
  src/main/resources/application.properties
Labels: status: planned, type: bug

#918 Fix ldap configuration properties in helm templates
  .examples/kubernetes/chart/urlaubsverwaltung/templates/deployment.yaml
Labels: status: ready-for-review

#921 Frontend asset tooling
  .nvmrc
  package-lock.json
  pom.xml
Labels: status: ready-for-review

#922 improve user role edit form
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/static/css/form.css
  src/main/resources/static/css/utility.css
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/tags/custom-head.tag
Labels: status: planned, status: ready-for-review

#834 #693: Remove html5 validation of addition and reduction of overtime
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned, status: ready-for-review, type: bug
