Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-10, with the labels that each got.

#831 Update spring boot to 2.1.9
  CHANGELOG.md
  pom.xml
Labels: dependencies, status: ready-for-review

#832 Add java 13 to github actions
  .github/workflows/maven.yml
Labels: status: ready-for-review

#825 Allow user to get their own data via the api
  src/main/docker/mariadb/Dockerfile
  src/main/docker/mariadb/more-connections.cnf
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/api/config/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/main/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurityTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiControllerSecurityIT.java
Labels: status: ready-for-review

#839 827 unified naming of username
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ReferredPerson.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestUser.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/UnknownPersonException.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/security/PersonSyncService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProvider.java
  src/main/resources/dbchangelogs/changelog-3.0.0-rename-login-to-username.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/user_creation.ftl
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/refer_form.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponseTest.java
  src/test/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/PersonSyncServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurityTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCronMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiControllerSecurityIT.java
Labels: status: needs-work
