Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-09, with the labels that each got.

#801 frontend dependecy update
  .nvmrc
  CHANGELOG.md
  package-lock.json
  package.json
  pom.xml
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/tags/head.tag
  src/main/webapp/components/calendar/calendar.spec.js
  src/main/webapp/components/calendar/index.js
  src/main/webapp/js/send-get-days-request-for-turn-of-the-year.js
  src/main/webapp/js/send-get-days-request.js
  src/main/webapp/js/send-get-department-vacations-request.js
  src/main/webapp/lib/date-fns/locale-resolver.js
  src/main/webapp/lib/date-fns/start-of-week.js
  src/test/javascript/test-setup-helper.js
Labels: status: waiting-for-reply

#730 gdpr compliant logging
  src/main/java/org/synyx/urlaubsverwaltung/account/domain/Account.java
  src/main/java/org/synyx/urlaubsverwaltung/account/service/TurnOfTheYearAccountUpdaterService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/VacationType.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplyForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/absence/Absence.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/department/Department.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/Overtime.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUser.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/Settings.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNote.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteType.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/test/java/org/synyx/urlaubsverwaltung/account/domain/AccountTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/VacationTypeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/absence/AbsenceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteFormTest.java
Labels: status: ready-for-review

#804 Add sonarcloud analyse to github action
  .github/workflows/maven.yml
  .travis.yml
  pom.xml
Labels: status: work-in-progress

#695 Secure Api Access
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/config/RestApiSecurityConfigIT.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiControllerSecurityIT.java
Labels: status: work-in-progress

#806 replace login name with person id for availability api
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/api/RestApiDateFormat.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityList.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityListDto.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerTest.java
Labels: topic: api

#634 Introduce application.properties based mail configuration
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailOptionProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailSender.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/SpringBootConfiguredMailOptionProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/SpringBootConfiguredMailSender.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/WebConfiguredMailOptionProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/WebConfiguredMailSender.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/config/MailConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/config/SpringBootConfiguredMailConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/config/WebConfiguredMailConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/web/SettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/web/SettingsViewController.java
  src/main/resources/application.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/updated_settings.ftl
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailSenderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/SpringBootConfiguredMailSenderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/WebConfiguredMailSenderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/config/SpringBootConfiguredMailConfigIT.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/config/WebConfiguredMailConfigIT.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/web/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/web/SettingsViewControllerTest.java
Labels: status: ready-for-review

#805 Default account and workingtime
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/account/config/AccountProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/config/ClockConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/config/WorkingTimeProperties.java
  src/main/resources/application.properties
  src/test/java/org/synyx/urlaubsverwaltung/account/service/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
Labels: status: ready-for-review, topic: configuration, type: enhancement

#807 Person manipulation can be restricted
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonViewControllerTest.java
Labels: status: ready-for-review

#812 Update Dependencies
  CHANGELOG.md
  pom.xml
Labels: dependencies, status: work-in-progress

#813 Upgrade maven wrapper to 3.6.2
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
Labels: status: ready-for-review

#814 Rename to view controller test
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: status: ready-for-review

#822 Fix user can be manipulated
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
Labels: status: ready-for-review

#809 move availability api to person resource
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerTest.java
Labels: topic: api

#823 show stacktraces ... it's important for our beta-phase
  src/main/java/org/synyx/urlaubsverwaltung/web/ExceptionHandlerControllerAdvice.java
Labels: status: ready-for-review

#828 Add default workdays to the configuration properties...
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/config/WorkingTimeProperties.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/config/WorkingTimePropertiesTest.java
Labels: status: ready-for-review
