Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2019-03, with the labels that each got.

#496 Upgrade maven wrapper to 3.6.0
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: CI/CD, Ready for Review

#500 Add sonarcloud via bob the builder
  .travis.yml
  README.md
  pom.xml
Labels: status: new, type: enhancement

#503 No sonar analysis for external PR
  .travis.yml
Labels: status: new, type: bug

#477 add International Women's Day holiday for Berlin
  CHANGELOG.md
  src/main/resources/Holidays_de.xml
Labels: status: needs-work, type: enhancement

#502 gravatar: use correct algorithmen to generate gravatar hash
  src/main/java/org/synyx/urlaubsverwaltung/core/person/GravatarUtil.java
  src/test/java/org/synyx/urlaubsverwaltung/core/person/GravatarUtilTest.java
Labels: status: new, type: bug

#505 Add yml to editorconfig
  .editorconfig
  pom.xml
Labels: status: new, type: enhancement

#504 Remove jib
  .travis.yml
  Dockerfile
  pom.xml
Labels: status: ready-for-review, topic: ci/cd, type: enhancement

#509 Replace accidently changed mysql connector back
  pom.xml
Labels: status: new, type: bug

#511 Remove OVERTIME and overtime hours from Application if over time is d…
  .travis.yml
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/VacationTypeService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/VacationTypeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplyForLeaveController.java
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/core/application/service/VacationTypeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/application/ApplyForLeaveControllerTest.java
Labels: status: ready-for-review, type: bug

#501 Spring boot 2 update
  CHANGELOG.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/ServletInitializer.java
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/config/ActiveDirectoryAuthConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/DefaultAuthConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LdapAuthConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/settings/SettingsServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNote.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/statistics/SickNoteStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/CalendarSyncServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapContextSourceForActiveDirectorySync.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapContextSourceForLdapSync.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapTemplate.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SimpleAuthenticationProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/web/ErrorController.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/spring-security-activeDirectory.xml
  src/main/resources/spring-security-default.xml
  src/main/resources/spring-security-ldap.xml
  src/main/resources/spring-security.xml
  src/test/java/org/synyx/urlaubsverwaltung/core/application/dao/ApplicationDAOIT.java
  src/test/java/org/synyx/urlaubsverwaltung/core/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/application/service/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/cron/CronMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceIntegrationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeDAOIT.java
  src/test/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/workingtime/OverlapServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/restapi/vacationoverview/VacationOverviewServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/LdapSyncServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/test/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/web/ExceptionHandlerControllerAdviceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/web/application/ApplicationValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/overtime/OvertimeControllerIT.java
  src/test/java/org/synyx/urlaubsverwaltung/web/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/statistics/SickDaysOverviewTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/statistics/UsedDaysOverviewTest.java
Labels: status: ready-for-review, type: enhancement

#519 Fix broken links in mails
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/core/application/domain/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/core/overtime/Overtime.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_user.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/application_cancellation_request.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_by_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cron_remind.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_application_by_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_applications.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/overtime_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/refer.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/rejected.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/sicknote_converted.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_second_stage_authority.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_user.ftl
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceIntegrationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/test/TestDataCreator.java
Labels: status: ready-for-review, topic: e-mails, type: bug

#523 Swagger upgrade
  CHANGELOG.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/config/SwaggerConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/BaseController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/absence/AbsenceController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/availability/AvailabilityController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/department/DepartmentController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/holiday/PublicHolidayController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/person/PersonController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/sicknote/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacation/VacationController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacationoverview/VacationOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/workday/WorkDayController.java
  src/main/resources/application.properties
  src/main/resources/static/api/css/reset.css
  src/main/resources/static/api/css/screen.css
  src/main/resources/static/api/images/explorer_icons.png
  src/main/resources/static/api/images/logo_small.png
  src/main/resources/static/api/images/pet_store_api.png
  src/main/resources/static/api/images/throbber.gif
  src/main/resources/static/api/images/wordnik_api.png
  src/main/resources/static/api/index.html
  src/main/resources/static/api/lib/backbone-min.js
  src/main/resources/static/api/lib/handlebars-1.0.0.js
  src/main/resources/static/api/lib/highlight.7.3.pack.js
  src/main/resources/static/api/lib/jquery-1.8.0.min.js
  src/main/resources/static/api/lib/jquery.ba-bbq.min.js
  src/main/resources/static/api/lib/jquery.slideto.min.js
  src/main/resources/static/api/lib/jquery.wiggle.min.js
  src/main/resources/static/api/lib/shred.bundle.js
  src/main/resources/static/api/lib/shred/content.js
  src/main/resources/static/api/lib/swagger-oauth.js
  src/main/resources/static/api/lib/swagger.js
  src/main/resources/static/api/lib/underscore-min.js
  src/main/resources/static/api/o2c.html
  src/main/resources/static/api/swagger-ui.js
  src/main/resources/static/api/swagger-ui.min.js
Labels: status: ready-for-review, topic: api, type: enhancement

#528 fix dependency conflict of guava: bump google api client to 1.25.0
  CHANGELOG.md
  pom.xml
Labels: status: ready-for-review, type: bug

#529 Use constructor injection instead of field injection in controllers
  src/main/java/org/synyx/urlaubsverwaltung/core/holiday/VacationOverview.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/availability/AvailabilityController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacationoverview/VacationOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapUserMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/web/account/AccountController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveDetailsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/department/DepartmentController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overtime/OvertimeController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overview/OverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/person/PersonController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/person/PersonManagementController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/sicknote/SickDaysOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/sicknote/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/statistics/ApplicationForLeaveStatisticsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/statistics/ApplicationForLeaveVacationOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/statistics/SickNoteStatisticsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/workingtime/WorkingTimeController.java
Labels: status: new, type: enhancement

#530 release script and documentation
  README.md
  release.sh
Labels: status: ready-for-review, topic: ci/cd, type: enhancement

#531 use hobby sized dynos
  app.json
Labels: status: ready-for-review, type: enhancement

#533 improve release docs
  README.md
  release.sh
Labels: status: ready-for-review, type: bug

#532 prometheus endpoint for metrics
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: status: ready-for-review, type: enhancement

#534 Remove guava fluentIterable
  src/main/java/org/synyx/urlaubsverwaltung/core/workingtime/OverlapService.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacation/VacationController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overview/OverviewController.java
  src/test/java/org/synyx/urlaubsverwaltung/core/workingtime/OverlapServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/overview/OverviewControllerTest.java
Labels: status: new, type: enhancement

#516 English translation
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/config/I18NConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/domain/ApplicationAction.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/domain/VacationCategory.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/domain/VacationType.java
  src/main/java/org/synyx/urlaubsverwaltung/core/mail/MailBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteCategory.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteType.java
  src/main/java/org/synyx/urlaubsverwaltung/core/statistics/ApplicationForLeaveStatisticsCsvExportServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/absence/AbsenceResponse.java
  src/main/resources/dbchangelogs/changelog-2.38.0-add-messagekey-to-vacationtype-and-sicknotetype.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_application_by_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_applications.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_second_stage_authority.ftl
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/main/webapp/WEB-INF/jsp/errors.jsp
  src/main/webapp/WEB-INF/jsp/login/login.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/tags/head.tag
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImplIT.java
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/test/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/statistics/SickDaysOverviewTest.java
Labels: status: ready-for-review, type: translation

#452 Exchange Kalender Integration mit Zeitzoneninformation
  CHANGELOG.md
  package.json
  src/main/java/org/synyx/urlaubsverwaltung/core/settings/ExchangeCalendarSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/exchange/ExchangeCalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/exchange/ExchangeFactory.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/exchange/ExchangeServiceException.java
  src/main/java/org/synyx/urlaubsverwaltung/web/settings/SettingsController.java
  src/main/resources/dbchangelogs/changelog-2.38.0-add-exchange-calendar-timezoneid.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/static/lib/jquery/css/ui-lightness/jquery-chosen-1.8.7.css
  src/main/resources/static/lib/jquery/js/jquery.chosen-1.8.7.js
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/tags/head.tag
  src/test/java/org/synyx/urlaubsverwaltung/core/sync/providers/exchange/ExchangeCalendarProviderTest.java
Labels: status: new, type: enhancement

#539 fix readme
  README.md
Labels: status: ready-for-review, type: bug

#538 h2 console is now available with the dev active
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfig.java
  src/main/resources/application-dev.properties
Labels: status: ready-for-review, type: bug

#540 prepare liquibase changelogs for next release
  src/main/resources/dbchangelogs/changelog-2.37.0-add-exchange-calendar-timezoneid.xml
  src/main/resources/dbchangelogs/changelog-2.37.0-add-messagekey-to-vacationtype-and-sicknotetype.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: ready-for-review, type: enhancement

#545 fix basic auth for rest api calls
  CHANGELOG.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfig.java
  src/test/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfigIT.java
Labels: status: ready-for-review, type: bug

#541 Fix tests to not throw exceptions
  src/main/java/org/synyx/urlaubsverwaltung/restapi/ApiExceptionHandlerControllerAdvice.java
  src/test/java/org/synyx/urlaubsverwaltung/restapi/availability/AvailabilityControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/restapi/workday/WorkDayControllerTest.java
Labels: status: ready-for-review, type: enhancement

#544 Replace RequestMapping with Get/Post/DeleteMapping
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/restapi/absence/AbsenceController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/availability/AvailabilityController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/department/DepartmentController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/holiday/PublicHolidayController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/person/PersonController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/sicknote/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacation/VacationController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/vacationoverview/VacationOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/workday/WorkDayController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/BaseController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/account/AccountController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveDetailsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/department/DepartmentController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/login/LoginController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overtime/OvertimeController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overview/OverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/person/PersonController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/person/PersonManagementController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/sicknote/SickDaysOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/sicknote/SickNoteController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/statistics/ApplicationForLeaveVacationOverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/statistics/SickNoteStatisticsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/workingtime/WorkingTimeController.java
Labels: status: ready-for-review, type: enhancement

#549 fix labeling for docker container
  pom.xml
Labels: status: ready-for-review, type: bug

#555 add github issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/vulnerability-report.md
Labels: status: ready-for-review

#557 missing english translation for EWS URL
  CHANGELOG.md
  src/main/resources/messages_en.properties
Labels: status: ready-for-review, type: bug

#556 Reactivate view options
  src/main/resources/application.properties
Labels: status: ready-for-review, type: enhancement

#553 Only use the minimum repository abstraction level that is needed
  src/main/java/org/synyx/urlaubsverwaltung/core/account/dao/AccountDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/dao/ApplicationCommentDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/dao/ApplicationDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeCommentDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/settings/SettingsDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteCommentDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/absence/AbsenceMappingDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/core/workingtime/WorkingTimeDAO.java
Labels: status: ready-for-review, type: enhancement

#552 Cleanup
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/core/application/service/CalculationServiceTest.java
Labels: status: ready-for-review, type: enhancement

#560 Translation of vacationtype quickfix
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImpl.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_application_by_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_applications.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_second_stage_authority.ftl
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImplIT.java
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/RecipientServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/test/TestDataCreator.java
Labels: status: ready-for-review, type: bug, type: translation

#561 remove coveralls plugin, code analysis is done by sonarcloud.
  pom.xml
Labels: status: ready-for-review, type: enhancement

#559 Add missing translations in vacation overview
  CHANGELOG.md
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/vacation_overview.jsp
Labels: status: ready-for-review, type: bug, type: translation

#565 Build correct url of login button
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/login/login.jsp
Labels: status: ready-for-review, type: bug

#514 Add k8s deployment with a helm chart
  .examples/README.md
  .examples/kubernetes/chart/urlaubsverwaltung/.helmignore
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/requirements.lock
  .examples/kubernetes/chart/urlaubsverwaltung/requirements.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/templates/NOTES.txt
  .examples/kubernetes/chart/urlaubsverwaltung/templates/_helpers.tpl
  .examples/kubernetes/chart/urlaubsverwaltung/templates/config.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/templates/deployment.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/templates/ingress.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/templates/secrets.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/templates/service.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/values-existing-mariadb.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/values-mariadb.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/values.yaml
  .gitignore
Labels: status: ready-for-review, topic: ci/cd

#551 Thiloplanz issue372 (only for merging)
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/core/account/service/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/util/DateUtil.java
  src/main/java/org/synyx/urlaubsverwaltung/core/workingtime/OverlapService.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveDetailsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/overview/OverviewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/person/PersonController.java
  src/main/resources/messages_de.properties
  src/main/webapp/WEB-INF/tags/account-left.tag
  src/test/java/org/synyx/urlaubsverwaltung/core/account/service/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/application/service/CalculationServiceTest.java
Labels: status: ready-for-review, type: bug

#568 Hide icons from font awesome in a11y
  src/main/resources/static/js/calendar.js
  src/main/resources/static/js/custom.js
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/errors.jsp
  src/main/webapp/WEB-INF/jsp/login/login.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_header.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/person/include/staff_list.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/person/staff_view.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/test/javascript/__snapshots__/calendar.spec.js.snap
Labels: status: ready-for-review, type: enhancement

#569 A11y: use <em> instead of <i>
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
Labels: status: ready-for-review, type: enhancement

#512 395 availability overview enhancement
  CHANGELOG.md
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/vacation_overview_js.jsp
Labels: status: ready-for-review, type: enhancement

#573 Create AUTHORS.md
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS.md
  CONTRIBUTING.md
Labels: status: work-in-progress, type: enhancement

#564 Feature/232 maven javadoc skip
  pom.xml
Labels: status: work-in-progress

#581 Use ' instead of "
  src/main/resources/static/js/custom.js
Labels: status: ready-for-review, type: bug

#522 Migrate code reprecations
  src/main/java/org/synyx/urlaubsverwaltung/config/WebMvcConfig.java
Labels: status: work-in-progress

#457 Fix for double account creation
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/core/account/service/AccountInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/account/service/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/web/account/AccountController.java
  src/main/resources/dbchangelogs/changelog-2.39.0-add-unique-constraint-year-and-person-id-to-account.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/core/account/dao/AccountDAOTest.java
  src/test/java/org/synyx/urlaubsverwaltung/core/account/service/AccountInteractionServiceImplTest.java
Labels: status: ready-for-review, type: blocker

#571 Add a separat security config for rest api
  src/main/java/org/synyx/urlaubsverwaltung/config/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfig.java
  src/test/java/org/synyx/urlaubsverwaltung/config/RestApiSecurityConfigIT.java
  src/test/java/org/synyx/urlaubsverwaltung/config/WebSecurityConfigIT.java
Labels: status: ready-for-review, topic: api, type: enhancement

#593 Dangling javadoc cleanup
  src/main/java/org/synyx/urlaubsverwaltung/core/util/CalcUtil.java
Labels: status: ready-for-review

#591 Remove editor template for class
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/ApplicationCommentServiceImpl.java
Labels: status: ready-for-review, type: enhancement

#589 #232 jdk8 javadoc
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/core/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/mail/MailService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/workingtime/WorkDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/restapi/availability/AvailabilityService.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplicationForLeaveDetailsController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplyForLeaveController.java
Labels: status: ready-for-review, type: enhancement

#588 Remove PropertiesUtil
  src/main/java/org/synyx/urlaubsverwaltung/core/util/PropertiesUtil.java
  src/test/java/org/synyx/urlaubsverwaltung/core/mail/MailServiceImplIT.java
Labels: status: ready-for-review, type: enhancement

#590 Use dynamic class lookup for logger
  src/main/java/org/synyx/urlaubsverwaltung/core/account/service/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/application/service/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/cron/CronMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/cron/TurnOfTheYearAccountUpdaterService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/mail/MailSender.java
  src/main/java/org/synyx/urlaubsverwaltung/core/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/person/GravatarUtil.java
  src/main/java/org/synyx/urlaubsverwaltung/core/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/settings/SettingsServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/CalendarSyncServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/exchange/ExchangeCalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/google/GoogleCalendarSyncProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/core/sync/providers/noop/NoopCalendarSyncProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/core/util/StartupService.java
  src/main/java/org/synyx/urlaubsverwaltung/core/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/TestDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapSyncService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/LdapUserDataImporter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/PersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SimpleAuthenticationProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/web/ExceptionHandlerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/web/application/ApplyForLeaveController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/settings/GoogleCalendarOAuthHandshakeController.java
Labels: status: ready-for-review, type: enhancement

#592 Remove CryptoUtil
  src/main/java/org/synyx/urlaubsverwaltung/core/util/CryptoUtil.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/test/java/org/synyx/urlaubsverwaltung/security/SimpleAuthenticationProviderTest.java
Labels: status: ready-for-review, type: enhancement

#598 Add stalebot configuration
  .github/stale.yml
Labels: status: ready-for-review

#597 Improve input fields
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/errors.jsp
  src/main/webapp/WEB-INF/jsp/login/login.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: ready-for-review
