Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-12, with the labels that each got.

#1580 Remove UserInterceptor
  src/main/java/org/synyx/urlaubsverwaltung/security/UserInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebMvcConfig.java
Labels: status: planned

#1582 Put all language configuration into config package
  src/main/java/org/synyx/urlaubsverwaltung/config/I18NConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptor.java
Labels: status: planned

#1586 use hasGlobalErrors as condition to show errors
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: planned

#1588 Make oidc scopes mandatory
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
Labels: status: planned

#1593 Use Opional as return type in repositories
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationCommentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCommentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/VacationTypeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
Labels: status: planned, type: enhancement

#1609 Remove other type of sicknote categories
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCategory.java
Labels: status: planned

#1635 read date string value from duet-date-picker component
  src/main/javascript/js/application/day-length-selector.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#1633 Convert var to const/let
  src/main/css/base.css
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/table-selectable/index.js
  src/main/javascript/components/table-sortable/index.js
  src/main/javascript/js/application/app-info.js
  src/main/javascript/js/application/app-statistics.js
  src/main/javascript/js/get-url-parameter.js
  src/main/javascript/js/person/overview.js
  src/main/javascript/js/person/person-list.js
  src/main/javascript/js/send-get-days-request-for-turn-of-the-year.js
Labels: status: planned

#1634 Deprecate availability api
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AbstractTimedAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityListDto.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityService.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/DayAvailability.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceException.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpans.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProvider.java
Labels: status: planned

#1641 Upgrade jetty jspc to 10.0.0
  pom.xml
Labels: java, status: planned, type: dependencies

#1614 Default Urlaubsanspruch pro UV Instanz über UI-Komponenten pflegbar machen
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountSettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/resources/application.properties
  src/main/resources/dbchangelogs/changelog-4.4.0-accountsettings-default-vacation-days.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
Labels: status: planned

#1643 Add separate row for overtime form in application to avoid design break
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#1649 Adds emails on holiday replacement
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_allow.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_apply.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_cancellation.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_edit.ftl
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned

#1662 Maximal vacation days can be 366
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountSettingsValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
Labels: status: planned

#1664 Add id on merge applications
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
Labels: status: planned

#1666 Fix mail delivery for holiday replacement on edit
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
Labels: status: planned

#1670 Nodejs update
  .nvmrc
  pom.xml
Labels: status: planned

#1660 overview hours and minutes
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/javascript/components/datepicker/datepicker.css
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#1672 printable pages
  src/main/css/components/print.css
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/person-box__.tag
Labels: status: planned

#1681 Fix test that failed every year on christmas eve
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveTest.java
Labels: status: planned

#1679 fix person metric
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/metrics/PersonMetrics.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/metrics/PersonMetricsTest.java
Labels: status: planned, type: bug

#1678 decimal hours input for overtime record
  src/main/css/components/form.css
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/tags/input-group.tag
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
Labels: status: planned
