Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-04, with the labels that each got.

#1018 consider 'de-XX' locales for date-fns translations additionally to 'de'
  .github/workflows/maven.yml
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/bundles/__tests__/date-fns-localized.spec.js
  src/main/webapp/bundles/date-fns-localized.js
Labels: status: planned

#1054 Improve height of datepicker months container to show last row
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/components/calendar/calendar.css
Labels: status: planned, status: ready-for-review, topic: ux

#1017 Enable calendar interaction for past days
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/webapp/components/calendar/__tests__/calendar.spec.js
  src/main/webapp/components/calendar/calendar.css
  src/main/webapp/components/calendar/calendar.spec.js
  src/main/webapp/components/calendar/index.js
  src/main/webapp/js/__tests__/parse-query-string.spec.js
Labels: status: planned, status: ready-for-review

#1065 Add application forwards into comments
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationAction.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCommentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
Labels: status: planned, status: ready-for-review
