Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-11, with the labels that each got.

#1469 Fix empty start/end date in period and that start must be before end
  src/main/java/org/synyx/urlaubsverwaltung/web/FilterPeriod.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FilterPeriodTest.java
Labels: status: planned

#1464 fix datepicker with preset date
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteForm.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsCsvExportServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/DateFormatAware.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FilterPeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/javascript/components/datepicker/__tests__/create-datepicker-instances.spec.js
  src/main/javascript/components/datepicker/create-datepicker-instances.js
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/main/webapp/WEB-INF/tags/filter-modal.tag
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsCsvExportServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/DateFormatAwareTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FilterPeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeFormTest.java
Labels: status: planned

#1472 Unify form actions for sicknotes
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: planned

#1323 Weekends are selectable
  src/main/javascript/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/calendar/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#1470 Remove old junit asserts with assertj and use parametrized tests
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationCommentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/VacationDaysLeftTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/VacationTypeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationCommentValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProviderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/UnknownDepartmentExceptionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/dev/TestUserDemo.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeCommentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/UnknownOvertimeExceptionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/SickDaysOverviewTest.java
  src/test/java/org/synyx/urlaubsverwaltung/period/PeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/period/WeekDayTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/AbsenceSettingsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/FederalStateTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/ExtendedSickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/UnknownSickNoteExceptionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/UsedDaysTest.java
  src/test/java/org/synyx/urlaubsverwaltung/util/DateUtilTest.java
  src/test/java/org/synyx/urlaubsverwaltung/validation/CronExpressionConstraintValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/AbstractNoResultFoundExceptionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/DecimalNumberPropertyEditorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/TimePropertyEditorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeValidatorTest.java
Labels: status: planned

#1494 Deactivate jpa open in view property
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: status: planned

#1493 Fix freemarker incompatibleImprovements
  src/main/java/org/synyx/urlaubsverwaltung/FreemarkerConfig.java
Labels: status: planned

#1492 Add english translations for edit a vacation for leave
  src/main/resources/messages_en.properties
Labels: status: planned

#1488 Catch IllegalArgumentException on company calendar
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalViewControllerTest.java
Labels: status: planned, topic: api, topic: calendar, type: bug

#1495 Remove not needed date-de-DE-1.0-Alpha-1.js library
  .eslintignore
  src/main/javascript/bundles/app-form.js
  src/main/javascript/lib/date-de-DE-1.0-Alpha-1.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: javascript, status: planned, type: dependencies

#1498 use common file extension for icalender mail attachment
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
Labels: status: planned, topic: calendar, type: bug

#1501 Fix correct display of instant on a jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
Labels: status: planned

#1505 Fix empty Filterperiod start and end date
  src/main/java/org/synyx/urlaubsverwaltung/web/FilterPeriod.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FilterPeriodTest.java
Labels: status: planned

#1506 remove never used application action
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationAction.java
Labels: status: planned, type: bug

#1072 Send information when revoke/cancel an application for leave
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationStatus.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ImpatientAboutApplicationForLeaveProcessException.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/RemindAlreadySentException.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/application_cancellation_request_applicant.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_by_office_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/rejected_information.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/revoked_applicant.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/revoked_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/revoked_not_applicant.ftl
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationRecipientServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewControllerTest.java
Labels: status: planned, topic: emails, type: enhancement

#1511 datepicker integration workingtime
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
Labels: status: planned, type: enhancement

#1514 Improve performance, logging and readability of persons, dev and workingtime
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ReferredPerson.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/ApplicationForLeaveDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoUser.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DepartmentDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DurationChecker.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/OvertimeRecordDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/SickNoteDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/period/WeekDay.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTime.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
Labels: status: planned, type: enhancement

#1509 style selectbox
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/refer_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/main/webapp/WEB-INF/tags/select.tag
Labels: status: planned

#1526 rename messageCode juli to july
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
Labels: status: planned

#1521 Do not show edit button on vacation overview for temprary allowed app…
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
Labels: status: planned

#1523 Remove encoding of standard password 'secret' for demodata with stati…
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoUser.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
Labels: status: planned

#1518 highlight required application for leave fields when vacation type ch…
  src/main/javascript/js/application/vacation-type-changed.js
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#1516 Create a big amount of active or inactive demodata users
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataProperties.java
Labels: status: planned

#1535 error message font size
  package-lock.json
  package.json
  src/main/css/components/form.css
  src/main/css/components/tabs.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/main/webapp/WEB-INF/tags/error-text.tag
  webpack.config.js
Labels: status: planned

#1519 Improve application view performance
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCronMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeave.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCronMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewControllerTest.java
Labels: status: planned, type: enhancement

#1541 Replace custom sql with rename column from liquibase
  src/main/resources/dbchangelogs/changelog-2.26.0-add-google-calendar-data.xml
  src/main/resources/dbchangelogs/changelog-4.0.0-add-timezone.xml
Labels: status: planned

#1543 Enable csrf for all view forms
  src/main/css/components/navbar.css
  src/main/css/style.css
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/javascript/bundles/common.js
  src/main/javascript/components/menu/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/login/login.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerCompanyCalendarSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerDepartmentCalendarSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerPersonCalendarSecurityIT.java
Labels: status: planned

#1549 Only validate overlap if period is ok of sicknotes
  src/main/java/org/synyx/urlaubsverwaltung/application/service/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/overlap/OverlapService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteValidatorTest.java
Labels: status: planned

#1544 Improve github workflows
  .github/workflows/maven-dependency-check.yml
  .github/workflows/maven-mutation-testing.yml
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: status: planned

#1552 Validate annual vacation days on the backend
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/tags/input-number.tag
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
Labels: status: planned

#1565 Display the actual and not the latest workingtime
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: status: planned

#1465 add public holidays in absence overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/DateRange.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/javascript/js/absences-overview.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
Labels: status: planned

#1563 Order workingtime first active first and show timespan
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeHistoryDto.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: status: planned

#1574 Cleanup and move application statistics package
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/UsedDays.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/UsedDaysOverview.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/web/ApplicationForLeaveStatisticsService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/UsedDaysOverviewTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/UsedDaysTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysTest.java
Labels: status: planned, type: enhancement
