Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-03, with the labels that each got.

#982 Reorder the css loading to fix wrong color of past months for overtime form
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
Labels: status: planned, status: ready-for-review, topic: calendar, type: bug

#981 Reorder the css loading to fix wrong color of past months for sick notes
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
Labels: status: ready-for-review, topic: calendar, type: bug

#975 Fix to use default form action instead of google handshake in settings
  CHANGELOG.md
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
Labels: status: planned, status: ready-for-review, type: bug

#980 Fix that a multiple day event ends one day to early
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned, status: ready-for-review, type: bug

#976 Fix to add au for one day not in sick note period
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteValidatorTest.java
Labels: status: planned, status: ready-for-review, type: bug

#974 Fix to allow vacation overview for department head
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurityTest.java
Labels: status: planned, status: ready-for-review, type: bug

#985 Fix timezone selection for exchange calendar
  CHANGELOG.md
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/js/settings/settings-form.js
Labels: status: planned

#977 Move absences to absence package and some minor cleanups
  src/main/java/org/synyx/urlaubsverwaltung/absence/Absence.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMapping.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingService.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceService.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceTimeConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsenceList.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarSyncService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarSyncServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/absence/AbsenceType.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/CalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/noop/NoopCalendarSyncProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentConstants.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceMappingServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceTimeConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarSyncServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProviderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/web/SettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/testdatacreator/TestDataCreator.java
Labels: status: planned

#987 Add sicknotes to calendar
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteDAO.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteServiceImplTest.java
Labels: status: planned, status: ready-for-review, topic: calendar

#986 bump terser-webpack-plugin
  package-lock.json
  package.json
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#988 Minor typo and comma fixes for calendar share feature
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
Labels: status: ready-for-review, topic: calendar

#992 Upgrade google api client and services calendar to 1.30.9
  pom.xml
Labels: dependencies, status: planned

#993 Upgrade micrometer to 1.3.5
  pom.xml
Labels: dependencies, status: planned

#994 Upgrade httpcore to 4.4.13
  pom.xml
Labels: dependencies, status: planned

#995 Upgrade httpclient to 4.5.12
  pom.xml
Labels: dependencies, status: planned

#1000 Upgrade frontend maven plugin to 1.9.1
  pom.xml
Labels: dependencies, status: planned

#998 Upgrade pitest maven plugin to 1.5.0
  pom.xml
Labels: dependencies, status: planned

#997 Upgrade editorconfig maven plugin to 0.0.11
  pom.xml
Labels: dependencies, status: planned

#999 Upgrade ical4j to 3.0.15
  pom.xml
Labels: dependencies, status: planned

#1001 Add enforce plugin to check for java 11 and maven 3.3.9
  pom.xml
Labels: status: planned, status: ready-for-review

#1002 Delete system.properties
  system.properties
Labels: status: planned

#1003 Upgrade owasp dependency check plugin to 5.3.1
  pom.xml
Labels: dependencies, status: planned

#1006 Refactor Dockerfile, changing base image, rename jvm configuration en…
  Dockerfile
Labels: status: planned

#1007 Add vacation days to overtime calender
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned, status: ready-for-review, topic: calendar

#1013 Long term caching
  package-lock.json
  package.json
  src/main/webapp/WEB-INF/assets-manifest.json
  webpack.config.js
Labels: status: planned, status: ready-for-review

#1014 Add navigate dependency to overtime overview
  CHANGELOG.md
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/bundles/overtime-overview.js
  webpack.config.js
Labels: status: planned, status: ready-for-review, topic: ux, type: bug
