Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-01, with the labels that each got.

#906 Add pitest (mutation testing) with workflow
  .github/workflows/mutation-testing.yml
  pom.xml
Labels: status: planned, status: ready-for-review

#930 Coverage/add coverage profile and configure jacoco
  .github/workflows/maven.yml
  pom.xml
Labels: status: planned

#925 Rename overtime validator to overtime form validator
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#926 Allow user with boss role to access /api/absences
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiControllerSecurityIT.java
Labels: status: planned, status: ready-for-review

#931 Upgrade jollyday to 0.5.10
  pom.xml
Labels: dependencies, status: planned

#932 Upgrade docker maven plugin to 0.32.0
  pom.xml
Labels: dependencies, status: planned

#934 Upgrade httpcore to 4.4.12
  pom.xml
Labels: dependencies, status: planned

#933 Dependency/google api
  pom.xml
Labels: dependencies, status: planned

#936 Remove distribution repository from pom
  pom.xml
Labels: status: planned, status: ready-for-review

#937 Remove sonatype snapshot repository
  pom.xml
Labels: status: planned, status: ready-for-review

#923 Add application properties to readme
  README.md
  src/main/resources/application.properties
Labels: status: needs-work, status: planned

#935 Add micrometer strackdriver integration
  CHANGELOG.md
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/GcpResourceTypeLabelMeterRegistryCustomizer.java
  src/main/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/StackdriverMetricsExportAutoConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/StackdriverProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/StackdriverPropertiesConfigAdapter.java
  src/main/resources/META-INF/spring.factories
  src/main/resources/application.properties
  src/test/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/GcpResourceTypeLabelMeterRegistryCustomizerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/StackdriverMetricsExportAutoConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/plattform/gcp/stackdriver/StackdriverPropertiesTest.java
  src/test/resources/application.properties
Labels: status: ready-for-review

#948 Upgrade spring boot to 2.1.12
  CHANGELOG.md
  pom.xml
Labels: dependencies, status: planned, status: ready-for-review

#940 Use correct controller advice for each controller exceptions
  src/main/java/org/synyx/urlaubsverwaltung/absence/api/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/api/ApiExceptionHandlerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/api/RestControllerAdviceMarker.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/ViewExceptionHandlerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
Labels: status: planned, status: ready-for-review

#949 Update send-get-department-vacations-request.js
  src/main/webapp/js/send-get-department-vacations-request.js
Labels: status: planned, type: bug
