Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2020-08, with the labels that each got.

#1174 Remove sensitive data from availability api
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpans.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProvider.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpansTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProviderTest.java
Labels: status: planned, status: ready-for-review, topic: api, type: bug

#1239 Add first end-to-end smoke test for the uv
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/ApplicationForLeaveCreateIT.java
  src/test/resources/application.properties
Labels: status: planned, status: ready-for-review, type: enhancement

#1240 Remove default file logging
  .examples/docker-compose/with-mariadb/application.properties
  .examples/kubernetes/chart/urlaubsverwaltung/templates/config.yaml
  .examples/kubernetes/yaml/urlaubsverwaltung.yml
  README.md
  src/main/resources/application-demodata.properties
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: status: planned, status: ready-for-review

#1247 Reduce visibility of the MailSenderService that is ...
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailSender.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailSenderService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailConfigurationIT.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailSenderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
Labels: status: planned, status: ready-for-review

#1228 Remove ResponseWrapper class
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsenceList.java
  src/main/java/org/synyx/urlaubsverwaltung/api/ResponseWrapper.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentsListWrapper.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/components/calendar/__tests__/calendar.spec.js
  src/main/webapp/components/calendar/index.js
  src/main/webapp/components/datepicker/create-datepicker-instances.js
  src/main/webapp/js/send-get-days-request-for-turn-of-the-year.js
  src/main/webapp/js/send-get-days-request.js
  src/main/webapp/js/send-get-department-vacations-request.js
  src/main/webapp/js/vacation-overview.js
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentResponseTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiControllerTest.java
Labels: status: planned, status: ready-for-review, topic: api

#1229 Use ResponseStatusException instead of ErrorResponse
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/api/ErrorResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/api/RestControllerAdviceExceptionHandler.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/api/ErrorResponseTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiControllerTest.java
Labels: status: planned, status: ready-for-review, topic: api

#1250 Vacation controller sensitivity data
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/js/send-get-department-vacations-request.js
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerTest.java
Labels: status: planned, status: ready-for-review

#1265 Readd specific wrappers
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsencesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentDto.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/holiday/api/PublicHolidaysDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonListResponse.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonResponseMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteDto.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNotesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/api/WorkDayDto.java
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/js/__tests__/send-get-department-vacations-request.spec.js
  src/main/webapp/js/send-get-department-vacations-request.js
  src/main/webapp/js/vacation-overview.js
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/calendar/VacationApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewServiceTest.java
Labels: status: ready-for-review

#1276 fix vacation overview json object naming
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/js/vacation-overview.js
Labels: status: planned, status: ready-for-review

#1254 Api security with oidc
  src/main/java/org/synyx/urlaubsverwaltung/api/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
Labels: status: planned, status: ready-for-review

#1255 Replace logout-path with logout-uri for oidc logout
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandler.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
  src/main/resources/application.properties
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandlerTest.java
Labels: status: planned, status: ready-for-review

#1274 Project configuration files
  .eslintrc
  .github/workflows/maven.yml
  babel.config.json
  jest.config.js
  package.json
Labels: status: planned, status: ready-for-review

#1267 Use greenmail 1.6 with junit5 support
  pom.xml
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
Labels: status: planned

#1249 Use eslint report in sonarcloud
  .eslintrc
  .github/workflows/maven.yml
  package.json
  pom.xml
Labels: status: planned, status: ready-for-review

#1288 remove unused method from view controller
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/ApplicationForLeaveVacationOverviewViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/ApplicationForLeaveVacationOverviewViewControllerTest.java
Labels: status: planned

#1269 department absence year overview
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/DayOfMonth.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewMonthDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewMonthDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/AbsenceOverviewPersonDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/ApplicationForLeaveVacationOverviewViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/static/css/utility.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/vacation_overview.jsp
  src/main/webapp/css/vacation-overview.css
  src/main/webapp/js/__tests__/__snapshots__/html-literal.spec.js.snap
  src/main/webapp/js/__tests__/html-literal.spec.js
  src/main/webapp/js/html-literal.js
  src/main/webapp/js/vacation-overview.js
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/ApplicationForLeaveVacationOverviewViewControllerTest.java
Labels: status: planned

#1291 1262 vacationoverview approvements
  src/main/webapp/WEB-INF/jsp/application/vacation_overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/web/ApplicationForLeaveVacationOverviewViewControllerTest.java
Labels: status: planned, status: ready-for-review

#1292 vacationoverview to absenceoverview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewPersonDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/VacationOverviewViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/vacation_overview.jsp
  src/main/webapp/bundles/absences-overview.js
  src/main/webapp/bundles/vacation-overview.js
  src/main/webapp/css/absences-overview.css
  src/main/webapp/js/absences-overview.js
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/VacationOverviewViewControllerTest.java
  webpack.config.js
Labels: status: planned

#1296 Add attendee/organizer to ical events
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned

#1297 Add no nofitications for boss role to fix removal of boss role
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonValidator.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
Labels: status: planned

#1294 Remove internal person management to add persons
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/jsp/person/person_form.jsp
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonManagementViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonViewControllerTest.java
Labels: status: planned
