Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-12, with the labels that each got.

#2477 Upgrade maven wrapper to 3.8.4
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, status: planned

#2493 Upgrade logback to 1.2.8
  pom.xml
Labels: topic: security, topic: privacy, status: planned, type: security

#2462 Benutze DateRange anstatt der letzten JodaTime Klasse "interval"
  src/main/java/org/synyx/urlaubsverwaltung/absence/DateRange.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/overlap/OverlapCase.java
  src/main/java/org/synyx/urlaubsverwaltung/overlap/OverlapService.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/DateRangeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overlap/OverlapServiceTest.java
Labels: type: enhancement, status: planned

#2445 improve calendar absence ui
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/datepicker/__tests__/create-datepicker.spec.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/javascript/components/datepicker/datepicker.css
  src/main/javascript/js/absences-overview.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
Labels: status: planned
