Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-05, with the labels that each got.

#2023 Add absence overview link to overview page
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
Labels: status: planned, topic: absence-overview, topic: ux

#2027 Improve demo data with gravatar based email adresses.
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
Labels: topic: ux, type: enhancement

#2030 Add paddingCssClass in person tag
  src/main/webapp/WEB-INF/tags/person.tag
Labels: status: planned

#2019 Improve absence overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/javascript/js/absences-overview.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned

#2022 Avatar auf der Abwesenheitsübersicht
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
Labels: status: planned, topic: absence-overview, topic: ux, type: enhancement

#2043 Avatarmenu hat nun die Information "Eingeloggt als"
  src/main/java/org/synyx/urlaubsverwaltung/web/MenuDataProvider.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/web/MenuDataProviderTest.java
Labels: status: planned

#2050 Mark today in absence overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/javascript/js/absences-overview.css
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#2064 Bump spring-boot-starter-parent from 2.4.5 to 2.4.6
  pom.xml
Labels: java, status: planned, type: dependencies

#2070 use anmelden/abmelden instead of login/logout
  src/main/resources/messages_de.properties
Labels: topic: translation, type: enhancement

#2075 urlaubsstatistik csv export Zeitraum beachten trotz individuellem date.pattern
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/tags/date.tag
  src/main/webapp/WEB-INF/tags/export.tag
Labels: status: planned

#2079 Unify Krankmeldung/Krankheit/Krank/..
  src/main/resources/messages_de.properties
Labels: status: planned

#2082 Fix lg/sm vertical margin of section (vacation, overtime) summary
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
Labels: status: planned

#2076 Datumsanzeige von bis als Fließtext
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/date-range.tag
Labels: status: planned, topic: accessibility, topic: translation, type: enhancement

#2080 Fix child au days on overview / add au days for small devices
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
Labels: status: planned
