Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-03, with the labels that each got.

#1866 Unify person, sicknote and vacation list avatar sizes
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
Labels: status: planned

#1867 bump nodejs to 14.16.0
  .nvmrc
  pom.xml
Labels: javascript, status: planned, type: dependencies

#1819 allow selection of multiple departments in absence overview
  src/main/css/components/multi-select.css
  src/main/css/style.css
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/tags/icons/dots-horizontal.tag
  src/main/webapp/WEB-INF/tags/multi-select-item.tag
  src/main/webapp/WEB-INF/tags/multi-select.tag
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#1869 Use default gravatar in menu if user does not use gravatar
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: status: planned

#1872 Improve GitHub Action workflows
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: status: planned

#1871 shareable ical calendar configuration redirect
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerTest.java
Labels: status: planned

#1856 Speichern wann eine Person einer Abteilung hinzugefügt wurde
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentMemberEmbeddable.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/resources/dbchangelogs/changelog-4.13.0-add-department-member-accession-date.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned, topic: department, type: enhancement

#1877 Entfernen von mutation testing
  .github/workflows/maven-mutation-testing.yml
  pom.xml
Labels: status: planned

#1876 Trigger direkt über GitHub Actions zum Releasen
  .github/release-notes.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: status: planned

#1901 Entfernen von Assert aufrufen
  src/main/java/org/synyx/urlaubsverwaltung/absence/Absence.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/VacationType.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/Overtime.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeComment.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/period/Period.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteType.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/VacationTypeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeCommentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/period/PeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteTypeTest.java
Labels: status: planned, type: enhancement

#1889 WorkingTime days default configuration via gui
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkTimeSettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeSettings.java
  src/main/resources/dbchangelogs/changelog-4.14.0-add-global-default-working-days.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/tags/checkbox.tag
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimePropertiesTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeSettingsTest.java
  tailwind.config.js
Labels: status: planned

#1899 uv.calendar.organizer has to be an email or null
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarProperties.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarPropertiesTest.java
Labels: status: planned

#1890 replace decimal input for overtime reduction in application
  src/main/java/org/synyx/urlaubsverwaltung/DurationConverter.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/ApplicationForLeaveDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/Overtime.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/tags/duration.tag
  src/main/webapp/WEB-INF/tags/hour-and-minute-input.tag
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/DurationConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
Labels: status: planned

#1907 Add unique constraint for calendars
  src/main/java/org/synyx/urlaubsverwaltung/calendar/Calendar.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendar.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendar.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendar.java
  src/main/resources/dbchangelogs/changelog-4.14.0-split-calendar-tables.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarRepositoryIT.java
Labels: status: planned

#1909 fix wording of overtime that can be cleared
  src/main/resources/messages_en.properties
Labels: topic: overtime, type: bug

#1918 Replace custom oidc logouthandler with OidcClientInitiatedLogoutSuccessHandler
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandler.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcLogoutHandlerTest.java
Labels: topic: authentication, topic: oidc, type: bug
