Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-04, with the labels that each got.

#1925 Fehlerhafte Schreibweise von "Wieviele"
  src/main/resources/messages_de.properties
Labels: status: planned, type: bug

#1908 Delete department calendars when deleting departments
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendar.java
  src/main/resources/dbchangelogs/changelog-4.15.0-delete-department-calendar-on-department-deletion.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned

#1926 Filter unwanted applications for overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#1933 Improve revoke emails
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/revoked_applicant.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/revoked_management.ftl
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
Labels: status: planned

#1939 Delete overtime minutes and hours on type change
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapperTest.java
Labels: status: planned

#1905 Adds reminder to notify the applicant that the vacation starts soon
  src/main/java/org/synyx/urlaubsverwaltung/application/ApplicationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/application/ApplicationSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCronMailConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationReminderMailConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationReminderMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/resources/dbchangelogs/changelog-4.15.0-add-upcoming-vacation-reminder.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_application_upcoming.ftl
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/ApplicationSettingsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationReminderMailConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationReminderMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImplTest.java
Labels: status: planned

#1943 Fehlerhafte Schreibweise von "calender"
  CHANGELOG.md
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarService.java
  src/main/javascript/js/settings/settings-form.js
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
Labels: status: planned, type: bug

#1868 Send cancelled calendar entries via mail
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalType.java
  src/main/resources/application-demodata.properties
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarPropertiesTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
  src/test/resources/application.properties
Labels: status: planned, topic: calendar

#1942 Introduce a new setting to disallow half-day absences, fixes #1870
  src/main/java/org/synyx/urlaubsverwaltung/application/ApplicationSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/period/DayLength.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiController.java
  src/main/resources/dbchangelogs/changelog-4.15.0-add-to-allow-half-day-absences.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiControllerTest.java
Labels: status: planned

#1961 Überstundenübersichtsseite modernisieren
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
Labels: status: planned, topic: overtime, topic: ux, type: enhancement

#1970 Change title of application form if edit
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#1972 Change title of department form if edit
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
Labels: status: planned

#1968 Duration in mail in readable format
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailService.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/overtime_office.ftl
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceTest.java
Labels: status: planned

#1952 Improve department overview
  src/main/css/components/form.css
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentDepartmentFormMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentDepartmentOverviewDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentDepartmentOverviewDtoMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentOverviewDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: status: planned

#1978 Clickable cancellation requests in calendar
  src/main/javascript/components/calendar/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#1862 Multiple replacements for a application for leave
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/HolidayReplacementEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationReplacementDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/HolidayReplacementDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/SelectableHolidayReplacementDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPropertyEditor.java
  src/main/resources/dbchangelogs/changelog-4.16.0-add-holiday-replacement.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_application_by_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_applications.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_allow.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_apply.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_cancellation.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_edit.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_application_upcoming.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_second_stage_authority.ftl
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/HolidayReplacementEntityTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPropertyEditorTest.java
Labels: status: planned

#1992 Anpassen von verschiedenen Farbschemata in den Fehlerfarben und Input-Buttons
  src/main/css/components/form.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned, topic: ux, type: enhancement

#1963 Personendetailsseite modernisieren
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/tags/account-entitlement.tag
  src/main/webapp/WEB-INF/tags/box.tag
  src/main/webapp/WEB-INF/tags/person.tag
  src/main/webapp/WEB-INF/tags/section-heading.tag
Labels: status: planned, topic: ux, type: enhancement

#1997 Only hide input on all selected holiday replacements
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#2005 keep table cell height for workingtime checkmark
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
Labels: status: planned

#1895 Allow to see department absences for own department
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Role.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/javascript/js/absences-overview.css
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/RoleTest.java
Labels: status: planned

#2009 Wrong calculation of vacation statistics on period spanning
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
Labels: status: planned

#2011 Take start and end date of period as boundary to calculate sicknote s…
  src/main/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerTest.java
Labels: status: planned
