Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-06, with the labels that each got.

#2046 Abwesenheitsübersicht mit halben und ganzen Urlaubstagen, Wochenende und Feiertag
  src/main/java/org/synyx/urlaubsverwaltung/absence/Absence.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceService.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DateRange.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewPersonDayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/ApplicationStatus.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHoliday.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/javascript/js/absences-overview.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#2105 use default federalState when there are no absence workingTime entries
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
Labels: status: planned

#2116 Flexible heights of datepicker on overview page
  src/main/javascript/components/calendar/calendar.css
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#2114 sicknote and vacation on overview for small devices
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
Labels: status: planned

#2112 Fix lg/sm vertical margin of section (sick notes) summary
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
Labels: status: planned

#2119 consider person workdays for absence calculation
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeave.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationReplacementDto.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/period/WeekDay.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/ExtendedSickNote.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTime.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeWriteService.java
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/period/WeekDayTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/web/ExtendedSickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: status: planned

#2123 fix missing applicationForLeaves in absence overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
Labels: status: planned

#2129 Fix absence overview with wrong working times
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
Labels: status: planned

#2133 improve absence overview for smaller screens and long usernames
  src/main/javascript/js/absences-overview.css
  src/main/javascript/js/absences-overview.js
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/avatar.tag
Labels: status: planned

#2132 allow selecting days of other month in datepicker
  package-lock.json
  package.json
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: new

#2115 End of sickpay improvements
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNote.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteSettingsValidator.java
  src/main/resources/dbchangelogs/changelog-4.16.0-add-holiday-replacement.xml
  src/main/resources/dbchangelogs/changelog-4.20.6-add-end-of-sickpay-notification-send.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/sicknote_end_of_sick_pay.ftl
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteTest.java
Labels: status: new

#2161 Upgrade spring boot parent to 2.4.8 and downgrade tomcat to 9.0.46
  pom.xml
Labels: java, status: planned, type: dependencies

#2163 fix avatar urls
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
Labels: status: planned

#2165 Fix vacation days left after april calculation
  src/main/java/org/synyx/urlaubsverwaltung/application/service/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
Labels: status: planned

#2152 vacation can be edited if only the days of the edited vacation is left
  src/main/java/org/synyx/urlaubsverwaltung/application/service/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/CalculationServiceTest.java
Labels: status: planned
