Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-02, with the labels that each got.

#1770 Stornierte, nicht genehmigte, Anträge auf der Übersicht anzeigen (revoked)
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
Labels: status: planned, type: enhancement

#1771 1645 note to replacement
  src/main/java/org/synyx/urlaubsverwaltung/application/domain/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationMapper.java
  src/main/javascript/bundles/app-form.js
  src/main/javascript/js/application/holiday-replacement-changed.js
  src/main/resources/dbchangelogs/changelog-4.10.0-add-replacement-note.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_allow.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_apply.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_cancellation.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_holiday_replacement_edit.ftl
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_list.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormTest.java
Labels: status: planned

#1769 Avoid to add same application multiple times by double clicking
  package-lock.json
  src/main/javascript/js/application/app-form.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#1781 Rename comment actions
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeComment.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeCommentAction.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteComment.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentAction.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewController.java
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeCommentTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImplTest.java
Labels: status: planned

#1782 Standardfarben von tailwind v2 verwenden
  src/main/css/components/form.css
  src/main/css/components/navigation.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/main/webapp/WEB-INF/jsp/calendarsharing/index.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/privacy-box.tag
  tailwind.config.js
Labels: status: planned, type: enhancement

#1778 Keycloak / oidc basierendes Beispiel hinzugefügt
  .examples/docker-compose/with-keycloak/README.md
  .examples/docker-compose/with-keycloak/docker-compose.yml
  .examples/docker-compose/with-keycloak/urlaubsverwaltung-realm-export.json
  .gitignore
  src/main/resources/application-keycloak.properties
Labels: topic: oidc, topic: security, type: enhancement

#1705 overtime repesentation with Duration type
  src/main/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/OvertimeRecordDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/DurationConverter.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/Overtime.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailRecordDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeListDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeListMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeListRecordDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/dbchangelogs/changelog-4.11.0-rename-overtime-hours-to-overtime-duration.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/overtime_office.ftl
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/tags/duration.tag
  src/main/webapp/WEB-INF/tags/overtime-left-box-narrow.tag
  src/main/webapp/WEB-INF/tags/overtime-left-box__.tag
  src/main/webapp/WEB-INF/tags/overtime-left.tag
  src/main/webapp/WEB-INF/tags/overtime-total-box-narrow.tag
  src/main/webapp/WEB-INF/tags/overtime-total-box__.tag
  src/main/webapp/WEB-INF/tags/overtime-total.tag
  src/main/webapp/WEB-INF/tags/overtime_person-box__.tag
  src/main/webapp/WEB-INF/tags/overtime_person.tag
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/application/dao/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/DurationConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#1795 Use toHours instead of ToHoursPart in duration tag
  src/main/webapp/WEB-INF/tags/duration.tag
Labels: status: planned

#1798 Increase menu avatar size of image to 32
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: status: planned

#1804 bump nodejs to 14.15.5
  .nvmrc
  pom.xml
Labels: status: planned

#1820 Downgrade to Spring Boot 2.4.1
  pom.xml
Labels: java, status: planned, type: dependencies

#1802 Bei Änderung des Jahres werden die Links auf "Mein Konto" angepasst
  src/main/webapp/WEB-INF/jsp/person/include/overview_header.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
Labels: status: planned, topic: ux, type: enhancement

#1801 Replace SpringFox with SpringDoc
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/api/SwaggerConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/api/SwaggerUiController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/api/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/web/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiController.java
  src/main/resources/application.properties
Labels: status: planned

#1805 Database cleanups
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/resources/application.properties
  src/main/resources/dbchangelogs/changelog-4.12.0-default-naming-strategy.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/resources/application.properties
Labels: status: planned, type: enhancement

#1808 move 'logout' into avatar popup
  src/main/javascript/bundles/common.js
  src/main/javascript/components/avatar-popup/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/Page.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/PageConditions.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/LoginPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OverviewPage.java
Labels: status: planned

#1854 Fix Department equals and hashCode
  src/main/java/org/synyx/urlaubsverwaltung/department/Department.java
Labels: status: planned
