Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-11, with the labels that each got.

#2406 Fix naming on apply for leave edit
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#2407 fix vertically aligned menu items
  src/main/resources/templates/_navigation.html
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: type: bug, status: planned

#2412 Improve build with go offline
  .github/workflows/build.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: status: planned

#2413 Remove not needed div and format
  src/main/resources/templates/_layout.html
Labels: status: planned

#2410 Cleanup jsps
  src/main/webapp/WEB-INF/jsp/absences/absences_overview.jsp
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/errors.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes_statistics.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
Labels: status: planned

#2411 Fix i18n ...
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptorConfigurer.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleModelInterceptor.java
  src/main/resources/application.properties
  src/main/resources/messages.properties
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptorConfigurerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleModelInterceptorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OvertimeDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteOverviewPage.java
  src/test/resources/application.properties
Labels: status: planned

#2417 Show temporary allowed in calendars
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#2418 Eslint update
  .eslintrc
  package-lock.json
  package.json
  src/main/javascript/bundles/__tests__/date-fns-localized.spec.js
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/holiday-service.js
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/javascript/js/application/app-form-day-length-change-listener.js
  src/main/javascript/js/application/app-form.js
  src/main/javascript/js/get-url-parameter.js
  src/main/javascript/js/parse-query-string.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: type: dependencies, status: planned, javascript

#2416 Allow office role with secondstage and departmenthead
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidator.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidatorTest.java
Labels: status: planned

#2414 Allow to configure half days for annual vacation days if half days are active
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsService.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
Labels: status: planned

#2419 Fix integer and half days validation
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
Labels: status: planned

#2421 Allow combination chef with department head and second stage
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidator.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidatorTest.java
Labels: status: planned

#2423 wrong link
  src/main/java/org/synyx/urlaubsverwaltung/api/SwaggerConfig.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/calendarsharing/index.jsp
Labels: status: planned

#2440 Anpassungen an Umbenennungen von Urlaub
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
Labels: status: planned

#2449 do not leak explicit absence info in overview
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#2443 Show persons of the absence statistic based on the role of the viewer
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
Labels: status: planned
