Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2021-07, with the labels that each got.

#2096 UI Tests für Krankmeldungen verbessert
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/TestMariaDBContainer.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/UITestInitializer.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/LoginPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteOverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNotePage.java
Labels: status: planned, topic: sick note, type: enhancement

#2175 Remove this and every subsequent useless "eq(...)" invocation; pass t…
  src/test/java/org/synyx/urlaubsverwaltung/application/service/ApplicationCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarSyncServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/SickNoteInteractionServiceImplTest.java
Labels: status: planned, type: enhancement

#2173 Improve docker compose example
  .examples/docker-compose/with-mariadb/docker-compose.yaml
Labels: status: planned

#2177 stick mariadb example to 10.5
  .examples/docker-compose/with-mariadb/docker-compose.yaml
Labels: status: planned

#2174 Aufräumen von CSS
  src/main/css/base.css
  src/main/css/components/legend.css
  src/main/css/components/table.css
  src/main/css/style.css
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/main/webapp/WEB-INF/tags/year-selector.tag
Labels: type: enhancement

#2178 add minimum overtime reduction value setting
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/resources/dbchangelogs/changelog-4.21.0-add-minimum-overtime-reduction-value.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/tags/hour-and-minute-input.tag
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettingsValidatorTest.java
Labels: status: planned

#2166 introduce overtime-reduction-without-application-active flag
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/dbchangelogs/changelog-4.21.0-add-overtime-reduction-without-application-active-flag.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettingsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#2170 Add setting to restrict write access to overtime records
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/MenuDataProvider.java
  src/main/resources/dbchangelogs/changelog-4.21.0-add-setting-overtime-write-privileged-only.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages_de.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeSettingsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/MenuDataProviderTest.java
Labels: status: planned

#2180 automatisches Hinzufügen der Urlaubsvertretung nach Auswahl
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewController.java
  src/main/javascript/bundles/app-form.js
  src/main/javascript/components/application-replacement-select/__tests__/application-replacement-select.spec.js
  src/main/javascript/components/application-replacement-select/application-replacement-select.js
  src/main/javascript/components/application-replacement-select/index.js
  src/main/javascript/components/textarea/__tests__/textarea.spec.js
  src/main/javascript/components/textarea/index.js
  src/main/javascript/js/__tests__/fetch.spec.js
  src/main/javascript/js/fetch.js
  src/main/resources/application.properties
  src/main/resources/templates/icons/icon-trash.html
  src/main/resources/templates/thymeleaf/application/application-form.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/web/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/resources/application.properties
Labels: status: planned
