Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-12, with the labels that each got.

#3436 fix some missing label associations
  src/main/javascript/components/calendar/calendar.css
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/main/resources/templates/thymeleaf/settings/calendar/google.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note_convert.html
Labels: status: planned

#3456 Vereinheitlichung der Beispiele mit Docker-Compose
  .examples/docker-compose/with-keycloak/README.md
  .examples/docker-compose/with-keycloak/docker-compose.yml
  .examples/docker-compose/with-keycloak/keycloak/Dockerfile
  .examples/docker-compose/with-keycloak/keycloak/import/urlaubsverwaltung-realm.json
  .examples/docker-compose/with-keycloak/keycloak/import/urlaubsverwaltung-users-0.json
  .examples/docker-compose/with-mariadb/application.properties
  .examples/docker-compose/with-mariadb/db.env
  .examples/docker-compose/with-mariadb/docker-compose.yaml
  .examples/docker-compose/with-multiinstance/docker-compose.yaml
  pom.xml
Labels: status: planned, topic: documentation, topic: oidc

#3462 Remove unused workDaysCountService#getWeekDaysCount
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountService.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
Labels: status: planned

#3463 Remove a lot unused code
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
Labels: status: planned

#3464 Fix sick note statistics for a sick note overlapping a whole year
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatistics.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsTest.java
Labels: status: planned

#3466 Fix sick note form rendering on validation error
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
Labels: status: planned

#3447 Vereinheitlichung der Thymeleaf-Fragment-Struktur
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/fragments/filter-modal.html
  src/main/resources/templates/fragments/print.html
  src/main/resources/templates/fragments/privacy-box.html
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/application/application-form.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/error.html
  src/main/resources/templates/thymeleaf/login/login.html
  src/main/resources/templates/thymeleaf/person/box.html
  src/main/resources/templates/thymeleaf/person/person-basedata.html
  src/main/resources/templates/thymeleaf/settings/absence-types/special-leave.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-holiday-replacement.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-upcoming-application.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-waiting-application.html
  src/main/resources/templates/thymeleaf/settings/absence/sick-days.html
  src/main/resources/templates/thymeleaf/settings/absence/vacation.html
  src/main/resources/templates/thymeleaf/settings/calendar/exchange.html
  src/main/resources/templates/thymeleaf/settings/calendar/google.html
  src/main/resources/templates/thymeleaf/settings/calendar/integration.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/overtime.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/public-holidays.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/time.html
  src/main/resources/templates/thymeleaf/settings/settings_form.html
  src/main/resources/templates/thymeleaf/user/user-settings.html
Labels: type: enhancement, status: planned

#3480 Trim nice name before generating avatar
  src/main/java/org/synyx/urlaubsverwaltung/avatar/AvatarController.java
  src/test/java/org/synyx/urlaubsverwaltung/avatar/AvatarControllerTest.java
Labels: status: planned

#3478 Day length change finds the correct person id
  src/main/javascript/js/application/app-form-day-length-change-listener.js
  src/main/resources/assets-manifest.json
Labels: status: planned

#3481 Upgrade to Spring Boot 2.6.13
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/GoogleCalendarOAuthHandshakeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarClientProvider.java
Labels: type: dependencies, status: planned, java

#3483 Migrations from 5.x branch that are no breakting changes
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteConvertFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeValidator.java
Labels: status: planned

#3484 Upgrade to Spring Boot 2.7.x
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/api/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/resources/dbchangelogs/changelog-4.15.0-delete-department-calendar-on-department-deletion.xml
  src/test/java/org/synyx/urlaubsverwaltung/avatar/AvatarControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
Labels: type: dependencies, status: planned, java

#3482 Improve user deletion logging
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
Labels: status: planned

#3488 Fix to find all departments with dh and ssa role
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned

#3477 extract creating / updating person into PersonOnSuccessfullyOidcLoginEventHandler
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandler.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandlerTest.java
Labels: topic: account, status: planned, topic: oidc

#2916 Zugriff auf Urlaubsverwaltung nur für bestimmte OIDC-User erlauben
  .examples/docker-compose/with-keycloak/keycloak/import/urlaubsverwaltung-realm.json
  .examples/docker-compose/with-keycloak/keycloak/import/urlaubsverwaltung-users-0.json
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/MissingGroupsClaimAuthorityException.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/UrlaubsverwaltungOAuth2UserService.java
  src/main/resources/application-keycloak.properties
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/UrlaubsverwaltungOAuth2UserServiceTest.java
Labels: type: enhancement, status: planned, topic: oidc

#3498 Fix PersonOnSuccessfullyOidcLoginEventHandler.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandler.java
  src/main/resources/application-keycloak.properties
Labels: type: bug, topic: authentication, status: planned, topic: oidc

#3507 Revert "Merge pull request #3477 from urlaubsverwaltung/split-PersonO…
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandler.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandlerTest.java
Labels: status: planned

#3476 sickdays on csv export with sick days
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsCsvExportService.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsCsvExportServiceTest.java
Labels: status: planned

#3486 Singular/Plural for german translation
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReplacementDto.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/application/app-sections/section-info.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
  src/main/resources/templates/thymeleaf/person/overview/section-sick-note.html
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
Labels: status: planned

#3521 Erhöhung der Berierefreiheit bei Tabellen
  src/main/resources/templates/thymeleaf/application/app-sections/section-progress.html
  src/main/resources/templates/thymeleaf/application/application-detail.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note.html
  src/main/resources/templates/thymeleaf/sicknote/sick_notes_statistics.html
Labels: type: enhancement, topic: ux, status: planned, topic: accessibility

#3439 Add anchors to person nice names and avatars
  src/main/css/components/table.css
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/resources/assets-manifest.json
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/fragments/section-heading.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/application/app-sections/section-progress.html
  src/main/resources/templates/thymeleaf/application/application-detail.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/overtime/overtime_details.html
  src/main/resources/templates/thymeleaf/person/box.html
  src/main/resources/templates/thymeleaf/person/person-basedata.html
  src/main/resources/templates/thymeleaf/person/person-overview-reduced.html
  src/main/resources/templates/thymeleaf/person/person_detail.html
  src/main/resources/templates/thymeleaf/person/person_permissions.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/sicknote/sick_days.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note.html
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
Labels: status: planned

#3534 fix missing date picker on sickDays overview
  src/main/resources/templates/thymeleaf/sicknote/sick_days.html
Labels: status: planned

#3532 ignore case when sorting/comparing strings
  src/main/java/org/synyx/urlaubsverwaltung/search/SortComparator.java
  src/test/java/org/synyx/urlaubsverwaltung/search/SortComparatorTest.java
Labels: status: planned

#3542 Revert "optional 'personId' parameter for avatar"
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/thymeleaf/application/application-form.html
  src/main/resources/templates/thymeleaf/person/person-overview-reduced.html
Labels: status: planned

#3543 fix avatar fallback image
  src/main/resources/templates/fragments/avatar.html
Labels: status: planned

#3510 Persons do not need an E-Mail-Address
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/exchange/ExchangeCalendarProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailSenderService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonCreatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonDisabledEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonUpdatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataDto.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/web/MailAddressValidationUtil.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/person/box.html
  src/main/resources/templates/thymeleaf/person/person-basedata.html
  src/main/resources/templates/thymeleaf/person/person_detail.html
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailSenderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
Labels: type: enhancement, status: planned

#3537 Show number of working days with and without aub on sick note details/form/overview
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/person/overview/section-sick-note.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note_convert.html
Labels: status: planned

#3531 fix person pagination
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
Labels: type: bug, status: planned

#3522 Suchen nach Mitarbeiter:innen bei Abteilungen
  src/main/css/components/form.css
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/javascript/bundles/department-form.js
  src/main/javascript/components/form/autosubmit.js
  src/main/resources/assets-manifest.json
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/sicknote/sick_days.html
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: topic: department, status: planned

#3417 Maven plugin oci image
  .github/workflows/release.yml
  Dockerfile
  pom.xml
Labels: status: planned

#3553 Remove version from login page
  src/main/java/org/synyx/urlaubsverwaltung/security/LoginController.java
  src/main/resources/templates/thymeleaf/login/login.html
  src/test/java/org/synyx/urlaubsverwaltung/security/LoginControllerTest.java
Labels: status: planned
