Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-05, with the labels that each got.

#2878 Only add department name to flashAttribute instead of whole form
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentForm.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: status: planned

#2880 Serializable SickNoteCommentForm
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentForm.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
Labels: status: planned

#2892 Rechtschreibfehler / Übersetzungen angepasst
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
Labels: type: enhancement, topic: translation, status: planned

#2891 Fix pro rata entitlement calculation on creation of account
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
Labels: status: planned

#2894 Verbesserungen der griechischen, österreichischen und englischen Übersetzungen
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: type: enhancement, topic: translation, status: planned

#2902 Remove approved in email notification for offices
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#2918 Display correct configuration of the calendarexport period
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#2926 fix absence overview colors
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayTypeColor.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeColor.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#2931 bump otel java agent to 1.14.0
  pom.xml
Labels: type: dependencies, status: planned, java

#2932 fix liquibase logging hell
  src/main/resources/application.properties
Labels: status: planned
