Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-04, with the labels that each got.

#2796 Set valid from of holiday account to first day of year
  src/main/java/org/synyx/urlaubsverwaltung/account/Account.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountForm.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/main/resources/dbchangelogs/changelog-4.36.0-renaming-accounts.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/webapp/WEB-INF/tags/account-entitlement-box__.tag
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
Labels: status: planned

#2799 Fix mapping to ApplicationForLeaveStatisticsDto
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsMapper.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
Labels: status: planned

#2800 Sets calendar entry for holiday replacement to free/available
  src/main/java/org/synyx/urlaubsverwaltung/absence/Absence.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned

#2808 bump nodejs to 16.14.2
  .nvmrc
  pom.xml
Labels: type: dependencies, status: planned

#2802 Remind person for vacation days
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderService.java
  src/main/resources/messages.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_expired_remaining_vacation_days.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_currently_left_vacation_days.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_remaining_vacation_days.ftl
  src/test/java/org/synyx/urlaubsverwaltung/TestContainersBase.java
  src/test/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceTest.java
Labels: status: planned

#2811 Order departments by name
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned

#2820 Send information to lohnfortzahlung directly after maximum sick pay days
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepository.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepositoryIT.java
Labels: status: planned

#2835 Fix calculation of lohnfortzahlung
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
Labels: status: planned

#2839 Login page as thymleaf template
  package.json
  src/main/css/login.css
  src/main/java/org/synyx/urlaubsverwaltung/security/LoginController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/MenuDataProvider.java
  src/main/resources/templates/icon/login.html
  src/main/resources/templates/thymeleaf/login/login.html
  src/main/webapp/WEB-INF/jsp/login/login.jsp
  src/test/java/org/synyx/urlaubsverwaltung/security/LoginControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/MenuDataProviderTest.java
Labels: status: planned

#2840 Calculate hours and not only hours part vor application overview
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewControllerTest.java
Labels: status: planned

#2851 Error-Logging wenn ein Benutzer sich aufgrund von nicht vorhandenen Daten (E-Mail, Benutzername, Vorname, Nachname) nicht anmelden kann
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
Labels: type: enhancement, topic: security, status: planned

#2623 Use spring session to dynamically update authorities of users
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationAuthoritiesFilter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationException.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SessionService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SessionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/WebSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/simple/SimpleAuthenticationProvider.java
  src/main/resources/application.properties
  src/main/resources/dbchangelogs/changelog-4.38.0-add-spring-session.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationAuthoritiesFilterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/SessionServiceImplTest.java
Labels: status: planned

#2856 Demodata with personnel number
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/webapp/WEB-INF/jsp/application/app_statistics.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
Labels: status: planned

#2846 New Crowdin updates
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: type: enhancement, topic: translation, status: planned

#2863 Move from deprecated adopt to temurin
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
  Dockerfile
Labels: status: planned
