Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-01, with the labels that each got.

#2513 Cleanup public holiday and provide a unified interface
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/period/DayLength.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHoliday.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountService.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
Labels: status: planned, topic: public holiday

#2527 Anzeigename bei E-Mail-Empfang ist "Urlaubsverwaltung"
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/resources/application.properties
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/resources/application.properties
Labels: type: enhancement, topic: emails, status: planned

#2514 Public holiday austria
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeHistoryDto.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/resources/Holidays_at.xml
  src/main/resources/dbchangelogs/changelog-4.28.0-add_country_to_federal_state.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/statistics/vacationoverview/api/VacationOverviewServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: status: planned, topic: public holiday

#2535 Add public holidays for switzerland
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_ch.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#2526 add austrian language
  src/main/css/components/checkbox-switch.css
  src/main/css/components/table.css
  src/main/javascript/bundles/__tests__/date-fns-localized.spec.js
  src/main/javascript/bundles/date-fns-localized.js
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/javascript/js/absences-overview.css
  src/main/resources/messages_at.properties
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: type: enhancement, topic: translation, status: planned

#2524 add opentelemetry agent to docker image
  Dockerfile
  pom.xml
Labels: type: enhancement, status: planned

#2529 Allow absences on public holidays
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTime.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/main/webapp/WEB-INF/jsp/workingtime/workingtime_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: status: planned

#2540 Add public holidays for the united kingdom
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_gb.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#2542 Fix incorrect termination criteria for working times per date range c…
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
Labels: status: planned

#2560 bump nodejs to 16.13.2
  .nvmrc
  pom.xml
Labels: type: dependencies, status: planned, javascript

#2562 Show absences on weekend in overview calendar and datepicker
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/datepicker/__tests__/create-datepicker.spec.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#2572 Filter persons of person details view that are duplicates
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
Labels: status: planned

#2578 Navigation wird bei der Druckansicht angezeigt
  pom.xml
  src/main/css/components/navigation.css
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/resources/templates/_navigation.html
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: type: bug

#2573 Show all departments of departmentHead/SSA combination
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
Labels: status: planned

#2585 Improve texts for calendar sharing
  src/main/css/base.css
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/error_calendar_sync.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/person_created_office.ftl
  src/main/webapp/WEB-INF/jsp/calendarsharing/index.jsp
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
Labels: status: planned

#2594 Add migration of federalstate thueringen
  src/main/resources/dbchangelogs/changelog-4.28.4-add_country_to_federal_state_for_missing_states.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: planned

#2598 Add employment ban as absence type
  src/main/resources/dbchangelogs/changelog-4.29.0-add-new-vacation-type-employment-ban.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#2592 Only show calendar share and absence overview for signed in user, boss and office
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/calendarsharing/index.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerDepartmentCalendarSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerPersonCalendarSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerTest.java
Labels: status: planned

#2601 change department name delimiter to :::
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewValidator.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewValidatorTest.java
Labels: status: planned

#2602 Improve department two stage approval text
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
Labels: status: planned

#2597 Allow application with remaining vacation days before april
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
Labels: status: planned

#2612 Make csv export accessable for excel
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
Labels: status: planned

#2564 Department Heads and SSA are allowed to watch members information
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRecipientServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurityTest.java
Labels: status: planned

#2618 Used wrong isOffice variable for action button cancel
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
Labels: status: planned

#2619 Show allow button only for department head if status is waiting
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
Labels: status: planned

#2620 Fix number of days until replacement/absence starts in emails
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailService.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_application_upcoming.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_holiday_replacement_upcoming.ftl
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailServiceTest.java
Labels: status: planned
