Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-07, with the labels that each got.

#3025 No cancellation approval needed if approval is not activated for this…
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentAction.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_directly_confirmation_applicant.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_directly_confirmation_office.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_directly_information_recipient_of_interest.ftl
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/cancel_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
Labels: status: planned

#3057 Add Temporary Allowed and Cancellation Requested Status to Overtime Reduction
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepository.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepositoryIT.java
Labels: status: planned

#3076 bump nodejs to 16.16.0
  .nvmrc
  pom.xml
Labels: type: dependencies, javascript

#3045 Move workingtime form to thymeleaf
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeHistoryDto.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/workingtime/workingtime_form.html
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewControllerTest.java
Labels: type: enhancement, topic: ux, status: planned

#3083 Configurable expiry date for remaining vacation days
  src/main/css/components/form.css
  src/main/java/org/synyx/urlaubsverwaltung/account/Account.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountForm.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysLeft.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/util/DateUtil.java
  src/main/javascript/js/account/account-form.js
  src/main/resources/dbchangelogs/changelog-4.43.0-add-account-expiry-date.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/notify_expired_remaining_vacation_days.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/remind_remaining_vacation_days.ftl
  src/main/resources/templates/fragments/datepicker-localization.html
  src/main/resources/templates/fragments/filter-modal.html
  src/main/resources/templates/fragments/vacation-type-colors-script.html
  src/main/resources/templates/fragments/year-selector.html
  src/main/resources/templates/thymeleaf/account/account_form.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/account/account_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/tags/account-left-box-narrow.tag
  src/main/webapp/WEB-INF/tags/account-left-box__.tag
  src/main/webapp/WEB-INF/tags/account-left.tag
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/VacationDaysLeftTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
Labels: status: planned

#3093 bump eslint-plugin-unicorn to 43.0.2
  .eslintrc
  package-lock.json
  package.json
Labels: type: dependencies, status: planned, javascript

#3102 fix person link on person-basedata page
  src/main/css/components/icon-link.css
  src/main/resources/templates/thymeleaf/person/person-basedata.html
Labels: type: bug, status: planned

#3112 Update maven wrapper to 3.8.6
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, status: planned, java

#3122 Update mailhog to 1.0.1
  docker-compose.yml
Labels: type: dependencies

#3111 Set expiry_notification_sent_date for all accounts from 2022 to the past
  src/main/resources/dbchangelogs/changelog-4.43.1-add-account-expiry-date-default-expiry.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: planned

#3124 Fix to all applications where the start or end date is overlapping th…
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#3096 Overview accessibility tweaks
  src/main/javascript/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/calendar/index.js
  src/main/javascript/js/person/overview.js
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/fragments/print.html
  src/main/resources/templates/fragments/year-selector.html
  src/main/resources/templates/thymeleaf/account/account_form.html
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
  src/main/resources/templates/thymeleaf/person/overview/section-calendar.html
  src/main/resources/templates/thymeleaf/person/overview/section-overtime.html
  src/main/resources/templates/thymeleaf/person/overview/section-sick-note.html
  src/main/resources/templates/thymeleaf/person/overview/section-vacation-days.html
  src/main/resources/templates/thymeleaf/person/person-overview.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/tags/year-selector.tag
Labels: type: enhancement, status: planned, topic: accessibility

#3127 responsive overview calendar
  src/main/javascript/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/calendar/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#3103 a11y: add link descriptions
  src/main/resources/templates/fragments/print.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/print.tag
Labels: status: planned

#3130 improve date today highlighting calendar/datepicker
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#3133 Fix working time error for workdays
  src/main/resources/templates/thymeleaf/workingtime/workingtime_form.html
Labels: status: planned

#3131 Abteilungs-Seiten werden nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentForm.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/messages_fr.properties
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/department/department_list.html
  src/main/webapp/WEB-INF/jsp/department/department_form.jsp
  src/main/webapp/WEB-INF/jsp/department/department_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: type: enhancement, topic: ux, topic: department, status: planned

#3138 responsive calendar
  src/main/javascript/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/calendar/index.js
  src/main/javascript/js/person/overview.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#3141 Accessibility departments
  src/main/css/components/form.css
  src/main/css/components/popover.css
  src/main/javascript/components/popover/index.js
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/department/department_list.html
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#3058 privileged user can create/edit/show sick notes and their statistics
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Role.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsRoleDto.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNote.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/MenuDataProvider.java
  src/main/resources/dbchangelogs/changelog-4.45.0-add-sick-note-applier.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/year-selector.html
  src/main/resources/templates/thymeleaf/account/account_form.html
  src/main/resources/templates/thymeleaf/person/overview/section-vacation-days.html
  src/main/resources/templates/thymeleaf/sicknote/sick_notes_statistics.html
  src/main/webapp/WEB-INF/jsp/person/person_detail.jsp
  src/main/webapp/WEB-INF/jsp/person/person_permissions.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes_statistics.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/MenuDataProviderTest.java
Labels: status: planned

#3142 remove jQuery dependency from calendar
  src/main/javascript/components/calendar/index.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned
