Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-08, with the labels that each got.

#3144 add user language setting
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptorConfigurer.java
  src/main/java/org/synyx/urlaubsverwaltung/config/LocaleModelInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleDto.java
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleModelInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/user/SupportedLocale.java
  src/main/java/org/synyx/urlaubsverwaltung/user/SupportedLocaleService.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsAwareSessionLocaleResolver.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsDtoValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserThemeDataProvider.java
  src/main/javascript/bundles/__tests__/date-fns-localized.spec.js
  src/main/javascript/bundles/date-fns-localized.js
  src/main/javascript/bundles/user-settings.js
  src/main/javascript/components/calendar/__tests__/__snapshots__/calendar.spec.js.snap
  src/main/javascript/components/tooltip/index.js
  src/main/javascript/js/user-settings/language-picker.js
  src/main/javascript/js/user-settings/theme-picker.js
  src/main/resources/dbchangelogs/changelog-4.45.0-add-user-locale.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/messages_fr.properties
  src/main/resources/static/images/flags/de.svg
  src/main/resources/static/images/flags/de_AT.svg
  src/main/resources/static/images/flags/el.svg
  src/main/resources/static/images/flags/en.svg
  src/main/resources/templates/_layout.html
  src/main/resources/templates/icon/globe.html
  src/main/resources/templates/thymeleaf/user/user-settings.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/tags/custom-head.tag
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleInterceptorConfigurerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/config/LocaleModelInterceptorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/LocaleConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/LocaleModelInterceptorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/SupportedLocaleServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsAwareSessionLocaleResolverTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsDtoValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserThemeDataProviderTest.java
Labels: status: planned

#3134 Add temporary allowed absence style for calendar
  src/main/css/components/color-picker.css
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewDayType.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/datepicker/datepicker-css-classes.js
  src/main/javascript/js/absences-overview.css
  src/main/resources/templates/fragments/section-heading.html
  src/main/resources/templates/fragments/year-selector.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/department/department_list.html
  src/main/resources/templates/thymeleaf/sicknote/sick_notes_statistics.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
Labels: status: planned

#3150 Verbesserung der Übersetzungen für Griechisch, Englisch, Österreichisch
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: type: enhancement, topic: translation, status: planned

#3160 fix person list account link visualisation
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/person/include/person_list.jsp
Labels: status: planned

#3166 Revert google api client version to latest compatiple
  pom.xml
Labels: status: planned

#3168 Verbessern von 'aria-current' bei der Jahresauswahl
  src/main/resources/templates/fragments/year-selector.html
Labels: type: enhancement, status: planned, topic: accessibility

#3170 GitHook zum automatischen formattieren hinzugefügt (pre-commit)
  README.md
  package-lock.json
  package.json
  scripts/githooks/pre-commit
  scripts/install-git-hooks.sh
Labels: type: enhancement, status: planned

#3169 Benutzerübersicht wird nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/icon/eye-off.html
  src/main/resources/templates/icon/eye.html
  src/main/resources/templates/icon/search.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/webapp/WEB-INF/jsp/person/person_view.jsp
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
Labels: type: enhancement, status: planned

#3052 Kalenderfreigabe wird nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarDto.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarDto.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarDto.java
  src/main/resources/messages.properties
  src/main/resources/templates/fragments/privacy-box.html
  src/main/resources/templates/thymeleaf/calendarsharing/index.html
  src/main/webapp/WEB-INF/jsp/calendarsharing/index.jsp
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerTest.java
Labels: type: enhancement, status: planned

#3176 Check if DH or SSA has the correct rights to add or edit sick notes
  src/main/java/org/synyx/urlaubsverwaltung/person/Role.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteValidatorTest.java
Labels: status: planned

#3181 fix applying absence for other person
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
Labels: status: planned

#3183 Fix relative path in frament replacements
  src/main/resources/templates/fragments/privacy-box.html
  src/main/resources/templates/thymeleaf/calendarsharing/index.html
  src/main/resources/templates/thymeleaf/person/persons.html
Labels: status: planned

#3171 Benutzer-Berechtigungen wird nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/person/person_permissions.html
  src/main/webapp/WEB-INF/jsp/person/person_permissions.jsp
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewControllerTest.java
Labels: type: enhancement, status: planned

#3177 Einstellungen werden nun mit Thymeleaf gerendert
  src/main/css/components/table.css
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/icon/speakerphone.html
  src/main/resources/templates/thymeleaf/settings/absence-types/absence-types.html
  src/main/resources/templates/thymeleaf/settings/absence-types/special-leave.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-holiday-replacement.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-upcoming-application.html
  src/main/resources/templates/thymeleaf/settings/absence/reminder-waiting-application.html
  src/main/resources/templates/thymeleaf/settings/absence/sick-days.html
  src/main/resources/templates/thymeleaf/settings/absence/vacation.html
  src/main/resources/templates/thymeleaf/settings/calendar/exchange.html
  src/main/resources/templates/thymeleaf/settings/calendar/google.html
  src/main/resources/templates/thymeleaf/settings/calendar/integration.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/default-workingtime.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/overtime.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/public-holidays.html
  src/main/resources/templates/thymeleaf/settings/public-holidays/time.html
  src/main/resources/templates/thymeleaf/settings/settings_form.html
  src/main/resources/templates/thymeleaf/user/user-settings.html
  src/main/webapp/WEB-INF/jsp/settings/absence-types/absence-types.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence-types/special-leave.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence/reminder-holiday-replacement.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence/reminder-upcoming-application.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence/reminder-waiting-application.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence/sick-days.jsp
  src/main/webapp/WEB-INF/jsp/settings/absence/vacation.jsp
  src/main/webapp/WEB-INF/jsp/settings/calendar/exchange.jsp
  src/main/webapp/WEB-INF/jsp/settings/calendar/google.jsp
  src/main/webapp/WEB-INF/jsp/settings/calendar/integration.jsp
  src/main/webapp/WEB-INF/jsp/settings/public-holidays/default-workingtime.jsp
  src/main/webapp/WEB-INF/jsp/settings/public-holidays/overtime.jsp
  src/main/webapp/WEB-INF/jsp/settings/public-holidays/public-holidays.jsp
  src/main/webapp/WEB-INF/jsp/settings/public-holidays/time.jsp
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
Labels: status: planned

#3178 Überstundenübersicht wird nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/templates/fragments/box.html
  src/main/resources/templates/fragments/rounded.html
  src/main/resources/templates/icon/arrow-down.html
  src/main/resources/templates/icon/arrow-up.html
  src/main/resources/templates/icon/reply.html
  src/main/resources/templates/thymeleaf/overtime/box.html
  src/main/resources/templates/thymeleaf/overtime/overtime_list.html
  src/main/resources/templates/thymeleaf/person/box.html
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
  src/main/resources/templates/thymeleaf/person/overview/section-overtime.html
  src/main/resources/templates/thymeleaf/person/overview/section-sick-note.html
  src/main/resources/templates/thymeleaf/person/overview/section-vacation-days.html
  src/main/resources/templates/thymeleaf/person/person_detail.html
  src/main/webapp/WEB-INF/jsp/overtime/overtime_list.jsp
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#3190 Zoneddatetime needs to be formatted via temporals and not dates
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
Labels: status: planned

#3191 Improve remaining vacation day not expire account information
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/person/person_detail.html
Labels: status: planned

#3195 account residual leave singular plural
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/person/person_detail.html
Labels: status: planned

#3197 Add personbasedata guard in person_detail
  src/main/resources/templates/thymeleaf/person/person_detail.html
Labels: status: planned

#3200 Fix wrong placeholder in message key
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#3193 New Crowdin updates
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#3207 Application edit form only requestable from person of the application
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned

#3172 introduce pagination for person list overview
  package-lock.json
  package.json
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/search/PageableSearchQuery.java
  src/main/java/org/synyx/urlaubsverwaltung/search/SortComparator.java
  src/main/java/org/synyx/urlaubsverwaltung/search/SortComparatorException.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlOptgroupDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlOptionDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlSelectDto.java
  src/main/javascript/bundles/person-view.js
  src/main/javascript/components/form/autosubmit.js
  src/main/javascript/components/form/index.js
  src/main/javascript/js/person/person-list.js
  src/main/resources/application.properties
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_layout.html
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/icon/chevron-left.html
  src/main/resources/templates/icon/chevron-right.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/search/SortComparatorTest.java
Labels: status: planned

#3204 Überstundeneingabe wird nun mit Thymeleaf gerendert
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/javascript/js/overtime/overtime-form.js
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/fragments/input-group.html
  src/main/resources/templates/icon/eye-off.html
  src/main/resources/templates/icon/eye.html
  src/main/resources/templates/icon/search.html
  src/main/resources/templates/icon/speakerphone.html
  src/main/resources/templates/thymeleaf/overtime/hour-and-minute-input.html
  src/main/resources/templates/thymeleaf/overtime/overtime_form.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: type: enhancement, topic: overtime, status: planned

#3209 Move section header in account_form out of form
  src/main/resources/templates/thymeleaf/account/account_form.html
Labels: status: planned

#3208 Rename and better declaration of the public holiday regulation
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/workingtime/workingtime_form.html
Labels: status: planned

#3214 Optimierung der Sprachauflösung in der Session
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleModelInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserLocaleChangedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsAwareSessionLocaleResolver.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsListener.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsService.java
  src/test/java/org/synyx/urlaubsverwaltung/user/LocaleConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsAwareSessionLocaleResolverTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsListenerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsServiceTest.java
Labels: type: enhancement, status: planned

#3233 Update nodejs to 16.17.0 and npm to 8.15.0
  .nvmrc
  pom.xml
Labels: type: dependencies, status: planned, javascript
