Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-09, with the labels that each got.

#3187 Verbessern der technischen Schnittstelle zum Anlegen und Editieren von Personen
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsRepositoryIT.java
Labels: type: enhancement, status: planned

#3224 Reactivate google calender tests and improve code
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarClientProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProvider.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/providers/google/GoogleCalendarSyncProviderServiceTest.java
Labels: status: planned

#3235 introduce isActive() method to person
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonCreatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonUpdatedEvent.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
Labels: type: enhancement, status: new, java

#3245 Footer on all pages
  src/main/css/base.css
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameDataProvider.java
  src/main/resources/templates/_footer.html
  src/main/resources/templates/_layout.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/calendarsharing/index.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/department/department_list.html
  src/main/resources/templates/thymeleaf/overtime/overtime_form.html
  src/main/resources/templates/thymeleaf/overtime/overtime_list.html
  src/main/resources/templates/thymeleaf/person/person-basedata.html
  src/main/resources/templates/thymeleaf/person/person-overview.html
  src/main/resources/templates/thymeleaf/person/person_detail.html
  src/main/resources/templates/thymeleaf/person/person_permissions.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/settings/settings_form.html
  src/main/resources/templates/thymeleaf/user/user-settings.html
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/app_notwaiting.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_details.jsp
  src/main/webapp/WEB-INF/jsp/overtime/overtime_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_convert.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note_form.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_notes.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FrameDataProviderTest.java
Labels: status: planned

#3236 Add csv export of sick notes
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/csv/CSVFile.java
  src/main/java/org/synyx/urlaubsverwaltung/csv/CsvExportException.java
  src/main/java/org/synyx/urlaubsverwaltung/csv/CsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonId.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedata.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteDetailedStatistics.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteDetailedStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/sicknote/sick_notes.html
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/csv/CsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteDetailedStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewControllerTest.java
Labels: status: planned

#3221 personoverview only for allowed departments
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
Labels: status: planned

#3253 fix Benutzerliste anzeigen nach Session Timeout
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/resources/templates/_layout.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
Labels: status: planned

#3265 fix alreadyUsedNextYear vacation days information on overview page
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
  src/main/resources/templates/thymeleaf/person/overview/section-vacation-days.html
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
Labels: status: planned

#3269 Fix choice pattern, so that do not format to integer and ...
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#3263 Add post logout redirect uri
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
Labels: status: planned

#3271 Fix that creation of SickNoteDetailedStatistics without department an…
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewControllerTest.java
Labels: status: planned

#3273 Respect higher permission on sick note csv statistics export
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsService.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsServiceTest.java
Labels: status: planned

#3286 improve responsive navigation
  pom.xml
  src/main/css/base.css
  src/main/css/components/dropdown-caret.css
  src/main/css/components/navigation.css
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/main/resources/static/fonts/kaushanscript/KaushanScript-Regular.woff
  src/main/resources/static/fonts/kaushanscript/KaushanScript-Regular.woff2
  src/main/resources/templates/_navigation.html
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/year-selector.tag
  tailwind.config.js
Labels: status: planned

#3202 privileged user department ssa boss application second
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeavePermissionEvaluator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Role.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsRoleDto.java
  src/main/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurity.java
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_by_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_by_management_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/cancelled_directly_confirmation_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/confirm_allowed_directly.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_application_by_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/new_directly_allowed_applications_by_management.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_second_stage_authority.ftl
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/temporary_allowed_user.ftl
  src/main/resources/templates/thymeleaf/person/person_permissions.html
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/cancel_form.jsp
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/security/UserApiMethodSecurityTest.java
  src/test/java/org/synyx/urlaubsverwaltung/vacations/VacationApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiControllerSecurityIT.java
Labels: status: planned

#3280 At least one person with office role
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidator.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDtoValidatorTest.java
Labels: status: planned
