Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-06, with the labels that each got.

#2951 Include cache in setup-java
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: status: planned

#2956 fix website scrolling on absence-type color selection
  src/main/javascript/components/color-picker/color-picker.js
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#2949 use absence-colors one nuance darker
  src/main/css/components/absence-color.css
Labels: status: planned

#2954 fix stacking context of color-picker on settings page
  src/main/webapp/WEB-INF/jsp/settings/settings_form.jsp
Labels: status: planned

#2950 fix vacation_types color migration script (set all to yellow)
  src/main/resources/dbchangelogs/changelog-4.39.0-add-vacation-type-color.xml
Labels: status: planned

#2958 bump nodejs to 16.15.1
  .nvmrc
  pom.xml
Labels: type: dependencies, status: planned, javascript

#2885 Show departments of user in person box
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/resources/templates/thymeleaf/application/application-form.html
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/person/overview.jsp
  src/main/webapp/WEB-INF/jsp/sicknote/sick_note.jsp
  src/main/webapp/WEB-INF/tags/person-box-narrow.tag
  src/main/webapp/WEB-INF/tags/person-box__.tag
  src/main/webapp/WEB-INF/tags/person.tag
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
Labels: status: planned

#2963 fix color-picker and copy-to-clipboard button in safari
  package-lock.json
  package.json
  src/main/css/components/color-picker.css
  src/main/resources/templates/_layout.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/tags/custom-head.tag
  webpack.config.js
Labels: status: planned

#2971 Upgrade jollyday to 0.8.0 and adapt jaxb dependencies
  pom.xml
Labels: type: dependencies, status: planned, java, topic: public holiday

#2979 spring boot 2.7
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/resources/dbchangelogs/changelog-4.15.0-delete-department-calendar-on-department-deletion.xml
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
Labels: status: planned

#2966 Two half absences are shown
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/javascript/components/calendar/calendar.css
  src/main/webapp/WEB-INF/assets-manifest.json
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
Labels: status: planned

#2981 fix missing morning absence color on hover
  src/main/javascript/components/calendar/calendar.css
  src/main/javascript/components/datepicker/datepicker.css
  src/main/webapp/WEB-INF/assets-manifest.json
Labels: status: planned

#3006 Office can refer absences
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/refer.ftl
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
Labels: status: planned

#3012 Add application time errors and fallbacks
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteForm.java
  src/main/java/org/synyx/urlaubsverwaltung/util/DateAndTimeFormat.java
  src/main/java/org/synyx/urlaubsverwaltung/web/DateFormatAware.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FilterPeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/web/InstantPropertyEditor.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sickdays/web/SickDaysOverviewViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/web/DateAndTimeFormatAwareTest.java
Labels: status: planned

#3000 Remove color of absence overview and person overview
  src/main/css/components/states.css
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/webapp/WEB-INF/jsp/person/include/overview_app_list.jsp
Labels: status: planned

#2986 Shedlock
  .examples/docker-compose/with-multiinstance/docker-compose.yaml
  .examples/docker-compose/with-multiinstance/nginx.conf
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/ScheduleLocking.java
  src/main/java/org/synyx/urlaubsverwaltung/config/SchedulerConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/ActiveDirectorySecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImportConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailConfiguration.java
  src/main/resources/dbchangelogs/changelog-4.41.0-add-shedlock.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/config/ScheduleLockingTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImportConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailConfigurationTest.java
Labels: status: planned

#3033 Add approver to allowed information mail to office and boss
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/allowed_office_boss.ftl
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
Labels: status: planned

#3040 Add precicion and default value for shedlock liquibase script
  src/main/resources/dbchangelogs/changelog-4.41.0-add-shedlock.xml
Labels: status: planned
