Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2022-11, with the labels that each got.

#3368 Add guard for account is available or not
  src/main/resources/templates/thymeleaf/person/overview/section-absences.html
Labels: status: planned

#3366 Add doRemainingVacationDaysExpireGlobally to account form
  src/main/resources/templates/thymeleaf/account/account_form.html
Labels: status: planned

#3372 fix helm chart for mariadb chart upgrade=11.3.3
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/README.md
  .examples/kubernetes/chart/urlaubsverwaltung/templates/deployment.yaml
Labels: status: planned

#3357 Move apps to thymeleaf
  src/main/css/components/button.css
  src/main/css/components/form.css
  src/main/css/components/select.css
  src/main/css/style.css
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/javascript/bundles/app-form.js
  src/main/javascript/js/application/__tests__/vacation-type-select.spec.js
  src/main/javascript/js/application/app-form.js
  src/main/javascript/js/application/vacation-type-changed.js
  src/main/javascript/js/application/vacation-type-select.js
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/fragments/section-heading.html
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/icon/emoji-happy.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-allow.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-cancel.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-decline-cancellation-request.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-edit.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-refer.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-reject.html
  src/main/resources/templates/thymeleaf/application/app-sections/action-remind.html
  src/main/resources/templates/thymeleaf/application/app-sections/section-info.html
  src/main/resources/templates/thymeleaf/application/app-sections/section-progress.html
  src/main/resources/templates/thymeleaf/application/app-sections/section-workingtime.html
  src/main/resources/templates/thymeleaf/application/application-detail.html
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/person/box.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note_form.html
  src/main/webapp/WEB-INF/assets-manifest.json
  src/main/webapp/WEB-INF/jsp/application/app_detail.jsp
  src/main/webapp/WEB-INF/jsp/application/app_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/action-buttons.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/allow_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/cancel_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/decline_cancellation_request_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/refer_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/reject_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/actions/remind_form.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_info.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_progress.jsp
  src/main/webapp/WEB-INF/jsp/application/include/app-detail-elements/app_workingtime.jsp
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned

#3362 Default packaging is jar. Provide *.war and *.jar on release
  .github/workflows/release.yml
  Dockerfile
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/ServletInitializer.java
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
Labels: status: planned

#3383 Verbesserung der GitHooks
  .githooks/post-merge
  .githooks/pre-commit
  README.md
  package.json
  scripts/install-git-hooks.sh
  src/main/css/icons/chevron-down-dark.svg
  src/main/css/icons/chevron-down.svg
  src/main/css/icons/chevron-up-dark.svg
  src/main/css/icons/chevron-up.svg
  src/main/css/icons/selector-dark.svg
  src/main/css/icons/selector.svg
Labels: type: enhancement, status: planned

#3381 Fix year display for overtime message
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#3388 Order department members by startdate
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
Labels: status: planned

#3385 Fix wrong parameter for overtime form employee change
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/javascript/js/overtime/overtime-form.js
  src/main/javascript/js/sick-notes/sick-note-form.js
  src/main/resources/assets-manifest.json
  src/main/resources/templates/thymeleaf/overtime/overtime_form.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note_form.html
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
Labels: status: planned

#3403 remove jquery-ui
  package-lock.json
  package.json
  src/main/css/components/jquery-ui-datepicker.css
  src/main/css/style.css
Labels: status: planned

#3410 Vereinheitlichung der mariadb version zu 10.6.11
  .examples/docker-compose/with-keycloak/docker-compose.yml
  .examples/docker-compose/with-mariadb/docker-compose.yaml
  .examples/docker-compose/with-multiinstance/docker-compose.yaml
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.lock
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.yaml
  .examples/kubernetes/yaml/urlaubsverwaltung-database.yml
  README.md
  docker-compose.yml
  src/test/java/org/synyx/urlaubsverwaltung/TestContainersBase.java
  src/test/java/org/synyx/urlaubsverwaltung/TestMariaDBContainer.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
Labels: status: planned

#3412 fix department selectbox layout
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
Labels: status: planned

#3414 Allow SSA and DH to view sick notes by department members
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/resources/templates/thymeleaf/person/person-overview.html
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
Labels: status: planned

#3420 Remove '/person/{personId}/edit'
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewControllerTest.java
Labels: status: planned

#3424 Add total number of remaining vacation days to turn of year mail
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterService.java
  src/main/resources/org/synyx/urlaubsverwaltung/core/mail/updated_accounts.ftl
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterServiceTest.java
Labels: status: planned

#3433 Fix dayLength is null on showHalfDayOption=false
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormTest.java
Labels: status: planned

#3427 Put progress of sick note beneath the person
  src/main/resources/templates/thymeleaf/sicknote/sick_note.html
Labels: status: planned

#3441 Use selected year instead of current year
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/templates/thymeleaf/overtime/overtime_list.html
Labels: status: planned

#3438 Move opencsv to be non-shaded via liquibase
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/csv/CsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteDetailedStatisticsCsvExportService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/csv/CsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteDetailedStatisticsCsvExportServiceTest.java
Labels: type: dependencies, status: planned

#3435 add acceptance test for application-for-leave creation with disabled half day
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/main/resources/templates/thymeleaf/settings/absence/vacation.html
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SettingsPage.java
Labels: status: planned
