Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-04, with the labels that each got.

#3754 Use selectedYear instead of currentYear for account link
  src/main/resources/templates/person/person_detail.html
Labels: status: planned

#3760 decline cancellation modal does not open on click
  src/main/resources/templates/application/app-sections/action-allow.html
  src/main/resources/templates/application/app-sections/action-cancel.html
  src/main/resources/templates/application/app-sections/action-decline-cancellation-request.html
  src/main/resources/templates/application/app-sections/action-refer.html
  src/main/resources/templates/application/app-sections/action-reject.html
Labels: status: planned

#3766 Only show dropdown for persons in overtime if persons list is not empty
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/templates/overtime/overtime_form.html
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#3767 No sorting of department member on error
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/resources/templates/department/department_form.html
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewControllerTest.java
Labels: status: planned

#3768 Place error into turbo frame to display
  src/main/resources/templates/application/application-statistics.html
Labels: status: planned

#3771 Add default mail notifications for new users
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonDTOMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonServiceExtensionImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CompanyCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/DepartmentCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/PersonCalendarRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/extension/PersonServiceExtensionImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapPersonContextMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ldap/LdapUserDataImporterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentEntityRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsRepositoryIT.java
Labels: status: planned

#3776 Dediziertes Lauchnpad verwenden (lib)
  pom.xml
  src/main/java/de/focusshift/launchpad/api/HasLaunchpad.java
  src/main/java/de/focusshift/launchpad/api/LaunchpadAppUrlCustomizer.java
  src/main/java/de/focusshift/launchpad/core/App.java
  src/main/java/de/focusshift/launchpad/core/AppDto.java
  src/main/java/de/focusshift/launchpad/core/AppName.java
  src/main/java/de/focusshift/launchpad/core/Launchpad.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadAutoConfiguration.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadConfigProperties.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadControllerAdvice.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadDto.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadService.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDeleteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/resources/application-demodata.properties
Labels: type: enhancement, status: planned

#3772 iOS fixes
  src/main/css/base.css
  src/main/css/components/navigation.css
  src/main/resources/templates/_navigation.html
Labels: status: planned

#3778 Fix apply for leave afterwards mysql
  src/main/resources/dbchangelogs/changelog-4.64.0-application-settings-apply-for-leave-afterwards.xml
Labels: status: planned

#3783 Fix launchpad layout
  src/main/resources/templates/launchpad/launchpad.html
Labels: type: bug, topic: ux, status: planned

#3621 memorize user pageable size
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/PageableDefaultSizeChangedEventConsumer.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsSupplier.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsSupplierImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/web/pageable/PageableConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/web/pageable/PageableDefaultSizeChangedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/web/pageable/PageableUserAwareArgumentResolver.java
  src/main/resources/dbchangelogs/changelog-4.65.0-add-user-pagination-settings.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/PageableDefaultSizeChangedEventConsumerIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/UserPaginationSettingsSupplierImplTest.java
  src/test/resources/application.properties
Labels: status: planned

#3734 Allow to disable gravatar globally
  src/main/java/org/synyx/urlaubsverwaltung/person/settings/AvatarSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/Settings.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameDataProvider.java
  src/main/resources/dbchangelogs/changelog-4.65.0-add-avatar-settings.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/settings/avatar/avatar.html
  src/main/resources/templates/settings/settings_form.html
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FrameDataProviderTest.java
Labels: status: planned

#3787 Introduce more specific mail notifications for managers (boss, department head and second stage authorities)
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/MailNotification.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonMailNotificationDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsDtoValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsMapper.java
  src/main/javascript/bundles/app-statistics.js
  src/main/javascript/bundles/department-form.js
  src/main/javascript/bundles/person-notifications.js
  src/main/javascript/bundles/persons.js
  src/main/javascript/bundles/sick-notes.js
  src/main/javascript/components/form/autosubmit.js
  src/main/javascript/components/form/index.js
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/assets-manifest.json
  src/main/resources/dbchangelogs/changelog-4.65.0-migrate-mail-notification-department-management.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/mail/application_temporary_allowed_to_management.txt
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/application/application-statistics.html
  src/main/resources/templates/department/department_form.html
  src/main/resources/templates/person/detail-section/person_detail_notifications.html
  src/main/resources/templates/person/person_notifications.html
  src/main/resources/templates/person/persons.html
  src/main/resources/templates/sicknote/sick_days.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRecipientServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewControllerTest.java
Labels: status: planned

#3809 Improve waiting reminder information
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/mail/application_remind_cron_to_management.txt
  src/main/resources/templates/application/application-overview.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
Labels: status: planned

#3806 Add overtime notifications by mail for own, department and all
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/MailNotification.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsDtoValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/dbchangelogs/changelog-4.65.0-migrate-mail-notification-overtime.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
  src/main/resources/mail/overtime_to_applicant_from_applicant.txt
  src/main/resources/mail/overtime_to_applicant_from_management.txt
  src/main/resources/mail/overtime_to_management.txt
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/person/detail-section/person_detail_notifications.html
  src/main/resources/templates/person/person_notifications.html
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewControllerTest.java
Labels: status: planned

#3813 Place permissions above notifications in user account
  src/main/resources/templates/person/person_detail.html
Labels: status: planned

#3810 send notifications mail after gaining more permissions
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/mail/person_gained_permissions.txt
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewControllerTest.java
Labels: status: planned

#3819 Add possibility to cancel workflows for same branch
  .github/workflows/build.yml
  .github/workflows/update-assets-manifest.yml
Labels: type: enhancement, status: planned
