Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-09, with the labels that each got.

#4008 Event-based demo data creation (4.x)
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DepartmentDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonCreatedEventListener.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/SickNoteDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/application/ApplicationEventRepublisher.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/sicknote/SickNoteEventRepublisher.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonServiceExtensionImpl.java
  src/main/resources/application-demodata.properties
Labels: status: planned

#4073 Upgrade Jollyday to 0.20.0
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceTest.java
Labels: type: dependencies, status: planned, java

#4086 fix editing sicknote
  src/main/resources/templates/sicknote/sick_note_form.html
Labels: status: planned

#4052 Event-based demo data creation (5.x)
  src/main/java/org/synyx/urlaubsverwaltung/application/specialleave/SpecialLeaveSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknotetype/SickNoteTypeServiceImpl.java
  src/main/resources/application-demodata.yaml
Labels: status: planned

#4034 use playwright to run ui tests instead of selenium & webdriver
  .github/workflows/build.yml
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/avatar/AvatarController.java
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/avatar.html
  src/test/java/org/synyx/urlaubsverwaltung/avatar/AvatarControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/Page.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/PageConditions.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/BrowserSetupExtension.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/PageParameterResolver.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/UITestInitializer.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/UiTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/UiTestStore.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/LoginPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OvertimeDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OvertimePage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SettingsPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteOverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNotePage.java
Labels: status: planned

#4125 Upgrade node version to 18.18.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript

#4126 Upgrade to jdk21
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
  .tool-versions
  CONTRIBUTING.md
  README.md
  pom.xml
Labels: status: planned

#4022 Use parameterized test instead of withmockuser
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewControllerPersonCalendarSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarApiControllerSecurityIT.java
Labels: status: planned

#4129 bump node to next lts 20.8.0
  .nvmrc
  pom.xml
Labels: type: dependencies, status: planned

#4135 4132 too much information
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/vacations/VacationApiControllerTest.java
Labels: status: planned

#4134 People should not see other vacations when creating a new one...
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/vacations/VacationApiControllerTest.java
Labels: status: planned

#4139 Order active vacation types by id
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknotetype/SickNoteTypeServiceImpl.java
  src/main/resources/templates/account/account_form.html
  src/test/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeEntityRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknotetype/SickNoteTypeServiceImplTest.java
Labels: status: planned
