Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-05, with the labels that each got.

#3822 fix falsy autosubmit behaviour
  src/main/javascript/components/form/autosubmit.js
  src/main/resources/assets-manifest.json
Labels: status: planned

#3820 fix history.back handling
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentForm.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteFormDto.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeForm.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeHistoryDto.java
  src/main/javascript/components/datepicker/__tests__/create-datepicker.spec.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/javascript/components/details-dropdown/index.js
  src/main/javascript/components/details-dropdown/turbo-before-render-restore.js
  src/main/javascript/js/application/app-statistics.js
  src/main/javascript/js/turbo/index.js
  src/main/javascript/js/turbo/on-turbo-before-render-restore.js
  src/main/resources/assets-manifest.json
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
Labels: status: planned

#3833 Fix multiple mails lohnfortzahlung after edit
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepository.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteRepositoryIT.java
Labels: status: planned

#3842 Add department head and second stage authority to list of refer
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/ResponsiblePersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/ResponsiblePersonServiceImpl.java
  src/main/resources/templates/application/app-sections/action-refer.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/ResponsiblePersonServiceImplTest.java
Labels: status: planned

#3846 Upgrade maven wrapper to 3.9.2
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, status: planned, java

#3854 Publish lifecycle events for SickNote
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteCancelledEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteCreatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteDeletedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteToApplicationConvertedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteUpdatedEvent.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImplTest.java
Labels: type: enhancement, topic: sick note, status: planned

#3855 Publish lifecycle events for Application
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationAllowedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationAllowedTemporarilyEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationAppliedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationCancellationRequestedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationCancelledEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationCreatedFromSickNoteEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationDeclinedCancellationRequestEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationDeletedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRejectedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRevokedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationUpdatedEvent.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
Labels: type: enhancement, topic: application, status: planned

#3863 Improve application mail service tests
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
Labels: status: planned

#3866 Unify wording of absences of colleagues
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/application/application-detail.html
Labels: status: planned

#3807 Notify colleagues about absence
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/MailNotification.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailService.java
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/mail/application_allowed_to_colleagues.txt
  src/main/resources/mail/application_cancellation_to_colleagues.txt
  src/main/resources/mail/sick_note_cancel_to_colleagues.txt
  src/main/resources/mail/sick_note_created_to_colleagues.txt
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/person/notifications/departments.html
  src/main/resources/templates/person/notifications/notification-card.html
  src/main/resources/templates/person/notifications/self.html
  src/main/resources/templates/person/person_notifications.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceTest.java
Labels: status: planned

#3864 On refer department head is not available if temporary allowed
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
Labels: status: planned

#3871 Add link to notifications into mails
  src/main/resources/MailMessages_de.properties
  src/main/resources/MailMessages_de_AT.properties
  src/main/resources/MailMessages_el.properties
  src/main/resources/MailMessages_en.properties
  src/main/resources/mail/application_allowed_directly_by_management_to_applicant.txt
  src/main/resources/mail/application_allowed_directly_to_applicant.txt
  src/main/resources/mail/application_allowed_directly_to_holiday_replacement.txt
  src/main/resources/mail/application_allowed_directly_to_management.txt
  src/main/resources/mail/application_allowed_to_applicant.txt
  src/main/resources/mail/application_allowed_to_colleagues.txt
  src/main/resources/mail/application_allowed_to_holiday_replacement.txt
  src/main/resources/mail/application_allowed_to_management.txt
  src/main/resources/mail/application_applied_by_applicant_to_applicant.txt
  src/main/resources/mail/application_applied_by_management_to_applicant.txt
  src/main/resources/mail/application_applied_to_holiday_replacement.txt
  src/main/resources/mail/application_applied_to_management.txt
  src/main/resources/mail/application_cancellation_request_declined_to_applicant.txt
  src/main/resources/mail/application_cancellation_request_declined_to_management.txt
  src/main/resources/mail/application_cancellation_request_to_applicant.txt
  src/main/resources/mail/application_cancellation_request_to_management.txt
  src/main/resources/mail/application_cancellation_to_colleagues.txt
  src/main/resources/mail/application_cancelled_by_management_to_applicant.txt
  src/main/resources/mail/application_cancelled_by_management_to_management.txt
  src/main/resources/mail/application_cancelled_directly_confirmation_by_applicant_to_applicant.txt
  src/main/resources/mail/application_cancelled_directly_confirmation_by_management_to_applicant.txt
  src/main/resources/mail/application_cancelled_directly_to_management.txt
  src/main/resources/mail/application_cancelled_to_holiday_replacement.txt
  src/main/resources/mail/application_cron_remind_for_upcoming_application_to_applicant.txt
  src/main/resources/mail/application_cron_upcoming_holiday_replacement_to_holiday_replacement.txt
  src/main/resources/mail/application_edited_by_applicant_to_applicant.txt
  src/main/resources/mail/application_edited_to_holiday_replacement.txt
  src/main/resources/mail/application_referred_to_management.txt
  src/main/resources/mail/application_rejected_information_to_applicant.txt
  src/main/resources/mail/application_rejected_information_to_management.txt
  src/main/resources/mail/application_remind_cron_to_management.txt
  src/main/resources/mail/application_remind_to_management.txt
  src/main/resources/mail/application_revoked_by_applicant_to_applicant.txt
  src/main/resources/mail/application_revoked_by_management_to_applicant.txt
  src/main/resources/mail/application_revoked_to_management.txt
  src/main/resources/mail/application_temporary_allowed_to_applicant.txt
  src/main/resources/mail/application_temporary_allowed_to_management.txt
  src/main/resources/mail/overtime_to_applicant_from_applicant.txt
  src/main/resources/mail/overtime_to_applicant_from_management.txt
  src/main/resources/mail/overtime_to_management.txt
  src/main/resources/mail/sick_note_cancel_to_colleagues.txt
  src/main/resources/mail/sick_note_created_to_colleagues.txt
  src/main/resources/mail/sicknote_converted.txt
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
Labels: status: planned
