Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-01, with the labels that each got.

#3577 Fix international womens day berlin and mv
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_de.xml
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#3561 fix person name link navigation
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/thymeleaf/absences/absences-overview.html
  src/main/resources/templates/thymeleaf/application/app-sections/section-progress.html
  src/main/resources/templates/thymeleaf/application/application-detail.html
  src/main/resources/templates/thymeleaf/application/application-overview.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/application/application_form.html
  src/main/resources/templates/thymeleaf/department/department_form.html
  src/main/resources/templates/thymeleaf/overtime/overtime_details.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/sicknote/sick_days.html
  src/main/resources/templates/thymeleaf/sicknote/sick_note.html
Labels: type: bug, status: planned

#3565 fix manual creation of holidays account with disabled vacation days expiration
  src/main/java/org/synyx/urlaubsverwaltung/account/Account.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountDraft.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/resources/templates/thymeleaf/person/person_detail.html
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountViewControllerTest.java
Labels: status: planned

#3582 Add public holidays for malta
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_mt.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#3596 Add smaller step size for annual vacation days
  src/main/resources/templates/thymeleaf/account/account_form.html
Labels: status: planned

#3598 Upgrade spring boot to version 2.7.7
  pom.xml
Labels: status: planned

#3592 Order links until sm with colum and after that as row...
  src/main/resources/templates/thymeleaf/person/overview/section-calendar.html
Labels: status: planned

#3599 Upgrade maven wrapper to 3.8.7
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, java

#3601 fix child sick days icon on overview
  src/main/resources/templates/fragments/box.html
  src/main/resources/templates/thymeleaf/person/overview/section-sick-note.html
Labels: status: planned

#3566 fix absences calculation for different federal states
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/overlap/OverlapService.java
  src/main/java/org/synyx/urlaubsverwaltung/period/DayLength.java
  src/main/java/org/synyx/urlaubsverwaltung/period/Period.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/CachedSupplier.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendar.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImplTest.java
Labels: status: planned

#3604 remove not used columns from database
  src/main/resources/dbchangelogs/changelog-4.59.0-remove-not-used-columns.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: planned

#3619 fix details-dropdown arrow issue on safari
  src/main/css/components/form.css
Labels: status: planned

#3620 100 und 200 anbieten für Pagination
  src/main/resources/templates/fragments/pagination.html
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/main/resources/templates/thymeleaf/person/persons.html
  src/main/resources/templates/thymeleaf/sicknote/sick_days.html
Labels: status: planned

#3551 Application export
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExport.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/thymeleaf/application/application-statistics.html
  src/test/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewControllerTest.java
Labels: status: planned

#3602 introduce extension mechanism
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/extension/ExtensionConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/ExtensionConfigurationProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonCreatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonUpdatedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonDTOMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonEventHandlerExtension.java
  src/main/java/org/synyx/urlaubsverwaltung/person/extension/PersonServiceExtensionImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/search/PageStreamSupport.java
  src/main/resources/loader.properties
  src/test/java/org/synyx/urlaubsverwaltung/person/extension/PersonDTOMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/extension/PersonEventHandlerExtensionTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/extension/PersonServiceExtensionImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/search/PageStreamSupportTest.java
Labels: type: enhancement, status: planned

#3633 introduce launchpad
  README.md
  src/main/css/components/navigation.css
  src/main/java/de/focusshift/launchpad/api/HasLaunchpad.java
  src/main/java/de/focusshift/launchpad/api/LaunchpadAppUrlCustomizer.java
  src/main/java/de/focusshift/launchpad/core/App.java
  src/main/java/de/focusshift/launchpad/core/AppDto.java
  src/main/java/de/focusshift/launchpad/core/AppName.java
  src/main/java/de/focusshift/launchpad/core/Launchpad.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadAutoConfiguration.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadConfigProperties.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadControllerAdvice.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadDto.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadService.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDeleteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
  src/main/javascript/bundles/common.js
  src/main/javascript/components/nav-popup-menu/index.js
  src/main/javascript/components/nav-popup-menu/nav-popup-menu.js
  src/main/javascript/components/navigation/index.js
  src/main/javascript/components/navigation/navigation-popup-menu.js
  src/main/resources/application.properties
  src/main/resources/assets-manifest.json
  src/main/resources/launchpad-core.properties
  src/main/resources/launchpad-core_en.properties
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/year-selector.html
  src/main/resources/templates/icon/chevron-down.html
  src/main/resources/templates/launchpad/launchpad.html
  src/main/resources/templates/thymeleaf/person/persons.html
Labels: status: planned
