Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-10, with the labels that each got.

#4156 Bump maven wrapper to version 3.9.5
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, status: planned, java

#4145 replace tablesorter dependency with custom code
  package-lock.json
  package.json
  src/main/css/bundles/absences-overview.css
  src/main/css/components/print.css
  src/main/css/components/table.css
  src/main/javascript/bundles/absences-overview.js
  src/main/javascript/bundles/department-list.js
  src/main/javascript/components/table-sortable/__tests__/table-sortable.spec.js
  src/main/javascript/components/table-sortable/index.js
  src/main/javascript/components/table-sortable/parser-data-value-number.js
  src/main/javascript/components/table-sortable/parser-date.js
  src/main/javascript/components/table-sortable/table-sortable.js
  src/main/javascript/js/absences-overview.js
  src/main/resources/templates/absences/absences-overview.html
  src/main/resources/templates/department/department_list.html
Labels: status: planned

#4152 remove datalist-polyfill
  package-lock.json
  package.json
  rollup.config.mjs
  src/main/javascript/js/common.js
  src/main/resources/templates/_layout.html
Labels: status: planned

#4169 Fix check if has enough vacation days if expiry date is set to first …
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
Labels: status: planned

#4170 Fix check if has enough vacation days if expiry date is set to first …
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
Labels: status: planned

#4155 js code cleanup
  src/main/css/bootstrap.less
  src/main/javascript/components/color-picker/color-picker.js
  src/main/javascript/components/details-dropdown/details-dropdown.js
  src/main/javascript/components/form/autosubmit.js
  src/main/javascript/components/popover/index.js
  src/main/javascript/js/__tests__/parse-query-string.spec.js
  src/main/javascript/js/application/app-form.js
  src/main/javascript/js/get-url-parameter.js
  src/main/javascript/js/parse-query-string.js
  src/main/javascript/js/person/overview.js
Labels: status: planned

#4179 fix rendering of default working time settings and vacation days
  src/main/resources/templates/settings/absence/vacation.html
  src/main/resources/templates/settings/settings_form.html
Labels: type: bug, status: planned

#4172 Add public holidays for croatia
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_hr.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#4181 4173 croatia public holidays
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_hr.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#4180 Vacation types message keys
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#4190 introduce VacationType DTOs in view models
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveForm.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormVacationTypeDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteConvertForm.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/resources/templates/application/application_form.html
  src/main/resources/templates/overtime/hour-and-minute-input.html
  src/test/java/org/synyx/urlaubsverwaltung/TestDataCreator.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/UsedDaysOverviewTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteConvertFormTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveCreateIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
Labels: status: planned

#4175 split settings view into multiple pages
  src/main/java/org/synyx/urlaubsverwaltung/application/application/SpecialLeaveItemDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/specialleave/SpecialLeaveSettingsItem.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeUpdate.java
  src/main/java/org/synyx/urlaubsverwaltung/person/settings/AvatarSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/AbsenceTypeSettingsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsencesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsencesValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsencesViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAvatarDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAvatarViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsCalendarSyncDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsCalendarSyncValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsCalendarSyncViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsWorkingTimeDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsWorkingTimeValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsWorkingTimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SpecialLeaveSettingsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SpecialLeaveSettingsItemDto.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/settings/absence-types/settings_absence_types.html
  src/main/resources/templates/settings/absences/reminder-holiday-replacement.html
  src/main/resources/templates/settings/absences/reminder-upcoming-application.html
  src/main/resources/templates/settings/absences/reminder-waiting-application.html
  src/main/resources/templates/settings/absences/settings_absences.html
  src/main/resources/templates/settings/absences/sick-days.html
  src/main/resources/templates/settings/absences/vacation.html
  src/main/resources/templates/settings/avatar/settings_avatar.html
  src/main/resources/templates/settings/calendar/settings_calendar_sync.html
  src/main/resources/templates/settings/fragments.html
  src/main/resources/templates/settings/public-holidays/settings_working_time.html
  src/main/resources/templates/settings/settings_form.html
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsencesValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsencesViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAvatarViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsCalendarSyncValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsCalendarSyncViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsWorkingTimeValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsWorkingTimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SettingsPage.java
Labels: status: planned

#4197 introduce ApplicationCommentEntity
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationComment.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentEntity.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentEntityTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceIT.java
Labels: status: planned

#4225 fix doubled demo persons creation
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
Labels: status: planned

#4226 Enable required explicit save for security context
  src/main/java/org/synyx/urlaubsverwaltung/dev/PersonDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationAuthoritiesFilter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SecurityWebConfiguration.java
  src/test/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationAuthoritiesFilterTest.java
Labels: status: planned

#4228 Improve helm chart to be ready for 5.x
  .examples/README.md
  .examples/kubernetes/chart/urlaubsverwaltung/Chart.lock
  .examples/kubernetes/yaml/urlaubsverwaltung-database-pvc.yml
  .examples/kubernetes/yaml/urlaubsverwaltung-database-secret.yml
  .examples/kubernetes/yaml/urlaubsverwaltung-database.yml
  .examples/kubernetes/yaml/urlaubsverwaltung.yml
  .github/workflows/helm-chart-release.yml
  .gitignore
  charts/README.md
  charts/urlaubsverwaltung/.helmignore
  charts/urlaubsverwaltung/Chart.lock
  charts/urlaubsverwaltung/Chart.yaml
  charts/urlaubsverwaltung/README.md
  charts/urlaubsverwaltung/templates/NOTES.txt
  charts/urlaubsverwaltung/templates/_helpers.tpl
  charts/urlaubsverwaltung/templates/deployment.yaml
  charts/urlaubsverwaltung/templates/hpa.yaml
  charts/urlaubsverwaltung/templates/ingress.yaml
  charts/urlaubsverwaltung/templates/secrets.yaml
  charts/urlaubsverwaltung/templates/service.yaml
  charts/urlaubsverwaltung/templates/serviceaccount.yaml
  charts/urlaubsverwaltung/templates/servicemonitor.yaml
  charts/urlaubsverwaltung/templates/tests/test-connection.yaml
  charts/urlaubsverwaltung/values.yaml
Labels: status: planned

#4232 Remove user-mapping configuration
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/api/JwtToPersonGrantedAuthoritiesConverter.java
  src/main/java/org/synyx/urlaubsverwaltung/api/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandler.java
  src/test/java/org/synyx/urlaubsverwaltung/api/JwtToPersonGrantedAuthoritiesConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/OidcPersonAuthoritiesMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandlerTest.java
Labels: status: planned

#4233 Upgrade to spring boot 3.2
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/validation/CronExpressionConstraintValidator.java
  src/main/resources/application.yaml
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteUIIT.java
  src/test/resources/application.yaml
Labels: status: planned

#4240 oidc role mapping should not be done on first login
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandler.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/PersonOnSuccessfullyOidcLoginEventHandlerTest.java
Labels: status: planned

#4241 Improve release and build process
  .github/workflows/build.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: type: enhancement, status: planned

#4245 ui test cleanup
  src/test/java/org/synyx/urlaubsverwaltung/ui/ApplicationForLeaveUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/OvertimeUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/SickNoteUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/ApplicationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/LoginPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/NavigationPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OvertimeDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OvertimePage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/OverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SettingsPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteDetailPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNoteOverviewPage.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SickNotePage.java
Labels: type: enhancement, status: planned
