Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2023-11, with the labels that each got.

#4256 Do not show transfer progress in maven builds
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: type: enhancement

#4257 Upgrade maven wrapper scripts to 3.2.0
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: status: planned

#4259 Add direct link from team badge to department absence overview
  src/main/resources/templates/person/box.html
Labels: status: planned

#4244 Provide provisioning via rest api for persons
  README.md
  src/main/java/org/synyx/urlaubsverwaltung/api/RestApiSecurityConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/api/RolesFromClaimMappersInfusedJwtAuthenticationConverter.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Role.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonProvisionDto.java
  src/main/java/org/synyx/urlaubsverwaltung/security/SecurityWebConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/MissingClaimAuthorityException.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMapperConverter.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMappersInfusedOAuth2UserService.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMappersProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromGroupsClaimMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromResourceAccessClaimMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/UrlaubsverwaltungOAuth2UserService.java
  src/test/java/org/synyx/urlaubsverwaltung/api/JwtToPersonGrantedAuthoritiesConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/api/RolesFromClaimMappersInfusedJwtAuthenticationConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMapperConverterTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMappersInfusedOAuth2UserServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromClaimMappersPropertiesTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromGroupsClaimMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromResourceAccessClaimMapperTest.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/UrlaubsverwaltungOAuth2UserServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarApiControllerSecurityIT.java
Labels: status: planned

#4267 fix missing text/messages for custom absence types
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#4268 enable approval/cancellation process for new vacation type by default
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesViewControllerTest.java
Labels: status: planned

#4266 add unique vacation type name validation
  src/main/css/components/form.css
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/ProvidedVacationType.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/AbsenceTypeSettingsDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/AbsenceTypeSettingsItemDto.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesDtoValidator.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/settings/absence-types/absence-types.html
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesDtoValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/settings/SettingsAbsenceTypesViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/CustomAbsenceTypeUIIT.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/pages/SettingsPage.java
Labels: status: planned

#4271 improve absence api and remove deprecated availibility api
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceService.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/DayAbsencesDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationStatus.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AbstractTimedAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityListDto.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityService.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/DayAvailability.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceException.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpans.java
  src/main/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/avatar/AvatarController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromResourceAccessClaimMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteStatus.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendar.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/main/javascript/components/calendar/__tests__/calendar.spec.js
  src/main/javascript/components/calendar/index.js
  src/main/javascript/components/datepicker/__tests__/create-datepicker.spec.js
  src/main/javascript/components/datepicker/create-datepicker.js
  src/main/javascript/js/absence/__tests__/absence-style-properties.spec.js
  src/main/javascript/js/absence/absence-criteria.js
  src/main/javascript/js/absence/absence-style-properties.js
  src/main/resources/templates/absences/absences-overview.html
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationStatusTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerSecurityIT.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/AvailabilityServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/FreeTimeAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/PublicHolidayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/SickDayAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/TimedAbsenceSpansTest.java
  src/test/java/org/synyx/urlaubsverwaltung/availability/api/VacationAbsenceProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteStatusTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarTest.java
Labels: status: planned

#4298 4291 improve api
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/api/SwaggerConfig.java
  src/main/java/org/synyx/urlaubsverwaltung/department/api/DepartmentApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayDto.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysDto.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerIT.java
Labels: status: planned

#4303 Improve docker compose example
  .examples/with-docker-compose/README.md
  .examples/with-docker-compose/docker-compose.yaml
Labels: status: planned

#4304 bump node to 20.9.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript

#4311 Add reply to to mail service and rename sender to from
  .examples/with-docker-compose/docker-compose.yaml
  README.md
  charts/urlaubsverwaltung/README.md
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailProperties.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailSenderService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/resources/application-demodata.yaml
  src/main/resources/application.yaml
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailSenderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/mail/MailServiceImplTest.java
  src/test/resources/application.yaml
Labels: status: planned

#4302 Fix absences of colleagues on zero department
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentService.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/vacations/VacationApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/vacations/VacationApiControllerTest.java
Labels: status: planned

#4312 Remove not needed security beans
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/OidcSecurityConfiguration.java
Labels: status: planned

#4329 Upgrade to spring boot 3.2 GA
  pom.xml
Labels: type: dependencies, status: planned, java

#4330 bump node to 20.10.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: status: planned

#4331 Change favicon to urlaubaer
  src/main/java/org/synyx/urlaubsverwaltung/security/SecurityWebConfiguration.java
  src/main/resources/static/browserconfig.xml
  src/main/resources/static/favicons/android-chrome-192x192.png
  src/main/resources/static/favicons/android-chrome-512x512.png
  src/main/resources/static/favicons/android-icon-144x144.png
  src/main/resources/static/favicons/android-icon-192x192.png
  src/main/resources/static/favicons/android-icon-36x36.png
  src/main/resources/static/favicons/android-icon-48x48.png
  src/main/resources/static/favicons/android-icon-72x72.png
  src/main/resources/static/favicons/android-icon-96x96.png
  src/main/resources/static/favicons/apple-icon-114x114.png
  src/main/resources/static/favicons/apple-icon-120x120.png
  src/main/resources/static/favicons/apple-icon-128x128.png
  src/main/resources/static/favicons/apple-icon-144x144.png
  src/main/resources/static/favicons/apple-icon-152x152.png
  src/main/resources/static/favicons/apple-icon-180x180.png
  src/main/resources/static/favicons/apple-icon-57x57.png
  src/main/resources/static/favicons/apple-icon-60x60.png
  src/main/resources/static/favicons/apple-icon-72x72.png
  src/main/resources/static/favicons/apple-icon-76x76.png
  src/main/resources/static/favicons/apple-icon-precomposed.png
  src/main/resources/static/favicons/apple-icon.png
  src/main/resources/static/favicons/apple-touch-icon.png
  src/main/resources/static/favicons/favicon-160x160.png
  src/main/resources/static/favicons/favicon-16x16.png
  src/main/resources/static/favicons/favicon-192x192.png
  src/main/resources/static/favicons/favicon-196x196.png
  src/main/resources/static/favicons/favicon-32x32.png
  src/main/resources/static/favicons/favicon-96x96.png
  src/main/resources/static/favicons/favicon.ico
  src/main/resources/static/favicons/favicon.png
  src/main/resources/static/favicons/ms-icon-144x144.png
  src/main/resources/static/favicons/ms-icon-150x150.png
  src/main/resources/static/favicons/ms-icon-310x310.png
  src/main/resources/static/favicons/ms-icon-70x70.png
  src/main/resources/static/favicons/mstile-150x150.png
  src/main/resources/static/favicons/safari-pinned-tab.svg
  src/main/resources/static/manifest.json
  src/main/resources/static/site.webmanifest
  src/main/resources/templates/_layout.html
Labels: status: planned
