Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2024-11, with the labels that each got.

#4968 bump node to 22.11.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript

#4969 [workflows] run all ui tests with all browsers
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/helm-chart-release.yml
  .github/workflows/issue-deplanned.yml
  .github/workflows/issue-planned.yml
  .github/workflows/issue-stale.yml
  .github/workflows/markdown-check.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
  pom.xml
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/PlaywrightTraceExtension.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/TestRecordVideoExtension.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/UiTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/pagination/PageableDefaultSizeChangedEventConsumerIT.java
Labels: type: enhancement, status: planned

#4959 public holidays: use public holidays from jollyday and not the custom…
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/resources/Holidays_at.xml
  src/main/resources/Holidays_be.xml
  src/main/resources/Holidays_ch.xml
  src/main/resources/Holidays_de.xml
  src/main/resources/Holidays_es.xml
  src/main/resources/Holidays_gb.xml
  src/main/resources/Holidays_gr.xml
  src/main/resources/Holidays_hr.xml
  src/main/resources/Holidays_it.xml
  src/main/resources/Holidays_lt.xml
  src/main/resources/Holidays_mt.xml
  src/main/resources/Holidays_nl.xml
  src/main/resources/Holidays_pl.xml
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkDaysCountServiceTest.java
  src/test/resources/Holidays_custom.xml
Labels: type: enhancement, status: planned

#4993 Remove swager default url special case that is not needed anymore
  src/main/java/org/synyx/urlaubsverwaltung/api/SwaggerConfig.java
  src/main/resources/application.yaml
Labels: type: enhancement, status: planned

#5000 Fix immutable Set in public holiday
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
Labels: status: planned

#5001 Change build image to builder-jammy-base to restore build mechanism a…
  pom.xml
Labels: type: bug, status: planned
