Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2024-10, with the labels that each got.

#4919 chart: add startup probe and remove support for k8s <= 1.18 in chart from 6.0.0
  charts/urlaubsverwaltung/Chart.yaml
  charts/urlaubsverwaltung/README.md
  charts/urlaubsverwaltung/templates/deployment.yaml
  charts/urlaubsverwaltung/templates/ingress.yaml
  charts/urlaubsverwaltung/templates/service.yaml
  charts/urlaubsverwaltung/templates/tests/test-connection.yaml
  charts/urlaubsverwaltung/values.yaml
Labels: status: planned

#4925 Upgrade maven wrapper to 3.9.9
  .mvn/wrapper/maven-wrapper.properties
Labels: type: dependencies, java

#4942 bump node to 22.10.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript
