Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2024-08, with the labels that each got.

#4765 Added lithuanian public holidays
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_lt.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#4838 Add belgium public holidays
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_be.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#4841 Add public holidays of poland
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/FederalState.java
  src/main/resources/Holidays_pl.xml
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/FederalStateTest.java
Labels: status: planned

#4836 Set ical timezone fixed to UTC
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned

#4840 Remove counter for comments
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentFormValidator.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteConvertFormValidator.java
  src/main/javascript/bundles/account-form.js
  src/main/javascript/bundles/app-detail.js
  src/main/javascript/bundles/app-form.js
  src/main/javascript/bundles/department-form.js
  src/main/javascript/bundles/overtime-form.js
  src/main/javascript/bundles/person-basedata.js
  src/main/javascript/bundles/sick-note-convert.js
  src/main/javascript/bundles/sick-note-form.js
  src/main/javascript/bundles/sick-note.js
  src/main/javascript/js/count.js
  src/main/javascript/js/max-chars.js
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/account/account_form.html
  src/main/resources/templates/application/app-sections/action-allow.html
  src/main/resources/templates/application/app-sections/action-cancel.html
  src/main/resources/templates/application/app-sections/action-decline-cancellation-request.html
  src/main/resources/templates/application/app-sections/action-reject.html
  src/main/resources/templates/application/application-form.html
  src/main/resources/templates/application/application_form.html
  src/main/resources/templates/department/department_form.html
  src/main/resources/templates/overtime/overtime_form.html
  src/main/resources/templates/person/person-basedata.html
  src/main/resources/templates/sicknote/sick_note_convert.html
  src/main/resources/templates/sicknote/sick_note_detail.html
  src/main/resources/templates/sicknote/sick_note_form.html
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentFormValidatorTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteConvertFormValidatorTest.java
Labels: status: planned

#4853 Ical4j3 downgrade - all day events with timezone incorrect
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: type: bug, topic: calendar, status: planned

#4855 bump node to 22.6.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned

#4867 create playwright trace report for failed ui tests
  .github/workflows/build.yml
  README.md
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/PlaywrightTraceExtension.java
  src/test/java/org/synyx/urlaubsverwaltung/ui/extension/UiTest.java
Labels: status: planned
