Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2024-06, with the labels that each got.

#4719 Remove thymeleaf-extras-springsecurity, because...
  pom.xml
Labels: type: bug, type: dependencies, status: planned, java

#4721 Diable csrf and session management for actuator endpoints
  src/main/java/org/synyx/urlaubsverwaltung/security/SecurityWebConfiguration.java
Labels: type: bug, topic: api, status: planned

#4743 Hide submitted sick notes on application overview
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewControllerTest.java
Labels: status: planned

#4742 Einheitliche Benennung von angenommenen Krankmeldungen
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/templates/sicknote/sick_note_detail.html
Labels: status: planned

#4747 Unify handler interface cleanup
  src/main/java/org/synyx/urlaubsverwaltung/infobanner/InfoBannerControllerAdvice.java
  src/main/java/org/synyx/urlaubsverwaltung/user/LocaleModelInterceptor.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserThemeDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/web/DataProviderInterface.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/web/PreloadAssetProvider.java
  src/test/java/org/synyx/urlaubsverwaltung/infobanner/InfoBannerControllerAdviceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserThemeDataProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FrameDataProviderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/PreloadAssetProviderTest.java
Labels: status: planned

#4748 unify date ranges in dashboard for submitted sicknotes
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/SickNoteDto.java
  src/main/resources/templates/application/application-overview.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/SickNoteDtoTest.java
Labels: status: planned

#4746 4745 overtime settings
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameDataProvider.java
  src/main/resources/templates/_navigation.html
  src/test/java/org/synyx/urlaubsverwaltung/web/FrameDataProviderTest.java
Labels: status: planned

#4749 Hide notifications for disabled sicknote submission by user
  src/main/java/org/synyx/urlaubsverwaltung/person/MailNotification.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/main/resources/templates/person/detail-section/person_detail_notifications.html
  src/main/resources/templates/person/notifications/departments.html
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewControllerTest.java
Labels: status: planned

#4720 Enable partial output while procession in thymeleaf...
  src/main/resources/application.yaml
Labels: type: enhancement, topic: ux, status: planned

#4750 Unify settings call in prepareApplicationForLeaveForm
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
Labels: status: planned

#4751 Remove deprecated getPublicHolidays methods
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidayApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/publicholiday/PublicHolidaysServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarServiceImplTest.java
Labels: type: enhancement, status: planned, topic: public holiday

#4757 Fix calculation if ical
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned

#4756 Improve ical tests with text blocks
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
Labels: status: planned
