Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2025-02, with the labels that each got.

#5132 Use TaskScheduler interface to get the default TaskScheduler based on…
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/config/SchedulerConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailConfiguration.java
  src/test/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailConfigurationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailConfigurationTest.java
Labels: status: planned

#5028 🎁 feat: Allow retrieving all users via API
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonApiController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerIT.java
Labels: status: planned

#5128 feat: add active flag to UserDto
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonMapper.java
  src/test/java/org/synyx/urlaubsverwaltung/person/api/PersonApiControllerIT.java
  src/test/java/org/synyx/urlaubsverwaltung/vacations/VacationApiControllerTest.java
Labels: status: planned

#5143 backup an inactive person with permission "INACTIVE"
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/PersonDataCollectionService.java
Labels: type: bug, status: planned

#5147 backup/restore: fix restore mapping dto -> WorkingTimeSettings
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/model/WorkingTimeSettingsDTO.java
  src/test/java/org/synyx/urlaubsverwaltung/extension/backup/model/WorkingTimeSettingsDTOTest.java
Labels: status: planned

#5131 Enable @Async with @EnableAsync
  src/main/java/org/synyx/urlaubsverwaltung/UrlaubsverwaltungApplication.java
  src/main/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderConfiguration.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderService.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailService.java
  src/test/java/org/synyx/urlaubsverwaltung/account/TurnOfTheYearAccountUpdaterServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonMailServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteMailServiceIT.java
Labels: type: bug, status: planned

#5160 Remove explicit naming of services
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonServiceImpl.java
Labels: status: planned

#5161 update ui test section in README
  README.md
Labels: status: planned

#5145 user locale: introduce AuthenticationSuccessEventListener
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsEventListener.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsEventListenerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/user/UserSettingsServiceTest.java
Labels: status: planned

#5173 Fix forgotten personIds as int to long
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarSharingViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonPropertyEditorTest.java
Labels: status: planned

#5174 Accepting a sick note creates a SickNoteAcceptedEvent
  pom.xml
  src/main/java/org/synyx/urlaubsverwaltung/extension/sicknote/SickNoteEventHandlerExtension.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteAcceptedEvent.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteInteractionServiceImplTest.java
Labels: status: planned

#5180 Use immutable toList() for collection streams
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationReminderMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/SpecialLeaveDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/specialleave/SpecialLeaveSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeViewModelService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/SettingsCalendarSyncViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/department/DepartmentServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentDepartmentOverviewDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/department/web/DepartmentViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/notification/UserNotificationSettingsServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overlap/OverlapService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeListMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/ResponsiblePersonServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/security/ReloadAuthenticationAuthoritiesFilter.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/AbsenceTypeSettingsDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SpecialLeaveSettingsDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/statistics/SickNoteStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/user/UserSettingsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeViewController.java
Labels: status: planned

#5181 Rename "record" method of overtime to not match a restricted identifier.
  src/main/java/org/synyx/urlaubsverwaltung/dev/OvertimeRecordDataProvider.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/PersonDataCollectionService.java
  src/main/java/org/synyx/urlaubsverwaltung/mail/MailRecipientServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/notification/UserNotificationSettings.java
  src/main/java/org/synyx/urlaubsverwaltung/notification/UserNotificationSettingsServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonNotificationsViewController.java
  src/test/java/org/synyx/urlaubsverwaltung/notification/UserNotificationSettingsServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceIT.java
Labels: status: planned

#5187 Cleanup violations, code style, ...
  README.md
  SECURITY.md
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/avatar/AvatarController.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/GoogleAuthorizationCodeFlowFactory.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/api/PersonMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/extend/SickNoteExtensionInteractionService.java
  src/main/java/org/synyx/urlaubsverwaltung/web/pageable/PageableConfiguration.java
  src/main/resources/MailMessages_en.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_navigation.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/avatar/SvgServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalViewControllerTest.java
Labels: status: planned

#5191 Remove bgb in special leave text
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#5186 Convert classes to records
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencePeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailVacationTypeDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/SpecialLeaveDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/export/ApplicationForLeaveExportViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/specialleave/SpecialLeaveSettingsItem.java
  src/main/java/org/synyx/urlaubsverwaltung/application/specialleave/SpecialLeaveSettingsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/vacationtype/VacationTypeDto.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/application/ApplicationEventHandlerExtension.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/PersonDataCollectionService.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/model/SickNoteCommentDTO.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/sicknote/SickNoteEventHandlerExtension.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/LeftOvertime.java
  src/main/java/org/synyx/urlaubsverwaltung/period/Period.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedata.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDetailsBasedataDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/settings/SpecialLeaveSettingsDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsCsvExportService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysStatisticsService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysStatisticsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/user/pagination/PageableDefaultSizeChangedEventConsumer.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FilterPeriod.java
  src/main/java/org/synyx/urlaubsverwaltung/web/NavigationDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlOptgroupDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlOptionDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/html/HtmlSelectDto.java
  src/main/java/org/synyx/urlaubsverwaltung/web/pageable/PageableDefaultSizeChangedEvent.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/LeftOvertimeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/period/PeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysDetailedStatisticsCsvExportServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FilterPeriodTest.java
  src/test/java/org/synyx/urlaubsverwaltung/web/FrameDataProviderTest.java
Labels: status: planned

#5201 Replace min max with Collections.min/max
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/extend/SickNoteExtendViewController.java
Labels: status: planned

#5202 Improve avatar loading when gravatar is disabled
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewMonthPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/web/AbsenceOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/SickNotePersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/avatar/AvatarController.java
  src/main/java/org/synyx/urlaubsverwaltung/avatar/SvgService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailPersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/Person.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/basedata/PersonBasedataDtoMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsDto.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonPermissionsMapper.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewDto.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/web/FrameDataProvider.java
  src/main/javascript/components/avatar/avatar.js
  src/main/javascript/components/avatar/index.js
  src/main/javascript/js/common.js
  src/main/resources/static/images/gravatar.jpg
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/absences/absences-overview.html
  src/main/resources/templates/application/app-sections/section-progress.html
  src/main/resources/templates/application/application-detail.html
  src/main/resources/templates/application/application-form.html
  src/main/resources/templates/application/application-overview.html
  src/main/resources/templates/application/application_form.html
  src/main/resources/templates/department/department_form.html
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/icon/avatar.html
  src/main/resources/templates/overtime/overtime_details.html
  src/main/resources/templates/person/box.html
  src/main/resources/templates/person/person-basedata.html
  src/main/resources/templates/person/person_detail.html
  src/main/resources/templates/person/persons.html
  src/main/resources/templates/sicknote/sick_days.html
  src/main/resources/templates/sicknote/sick_note_detail.html
  src/main/resources/templates/svg/avatar.svg
  src/test/java/org/synyx/urlaubsverwaltung/avatar/AvatarControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/avatar/SvgServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailPersonDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeDetailRecordDtoTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysOverviewViewControllerTest.java
Labels: status: planned

#5209 5208 calendar absence translation
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceType.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationMailService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarAbsence.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/CalendarAbsenceType.java
  src/main/java/org/synyx/urlaubsverwaltung/calendar/ICalService.java
  src/main/java/org/synyx/urlaubsverwaltung/calendarintegration/GoogleCalendarSyncProvider.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarAbsenceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/CalendarAbsenceTypeTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendar/ICalServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/calendarintegration/CalendarSyncServiceTest.java
Labels: status: planned

#5214 bump node to 22.14.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript
