Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2025-04, with the labels that each got.

#5293 Show error message on minimum overtime reduction
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidator.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveFormValidatorTest.java
Labels: status: planned

#5294 Fix demodata department creation with dh and ssa
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataCreationService.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DepartmentDataProvider.java
Labels: type: bug

#5308 Update help url
  src/main/java/org/synyx/urlaubsverwaltung/web/MenuProperties.java
  src/test/java/org/synyx/urlaubsverwaltung/web/MenuPropertiesTest.java
Labels: status: planned

#5321 Replace decathlon with spring changelog generator
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: type: enhancement, status: planned

#5260 application comment without edit
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeavePermissionEvaluator.java
  src/main/java/org/synyx/urlaubsverwaltung/application/comment/ApplicationCommentAction.java
  src/main/java/org/synyx/urlaubsverwaltung/comment/AbstractComment.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/model/ApplicationCommentActionDTO.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeComment.java
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/comment/SickNoteCommentEntity.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/application/app-sections/section-progress.html
  src/main/resources/templates/application/application_form.html
  src/main/resources/templates/overtime/overtime_form.html
  src/main/resources/templates/sicknote/sick_note_form.html
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/comment/AbstractCommentTest.java
Labels: status: planned

#5325 Add overtime comment directly
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/model/OvertimeCommentActionDTO.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeCommentAction.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeService.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeCommentFormDto.java
  src/main/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewController.java
  src/main/resources/messages.properties
  src/main/resources/messages_de_AT.properties
  src/main/resources/messages_el.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/overtime/overtime_details.html
  src/test/java/org/synyx/urlaubsverwaltung/overtime/OvertimeServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overtime/web/OvertimeViewControllerTest.java
Labels: status: planned

#5336 bump node to 22.15.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: status: planned, javascript, dependencies
