Repository urlaubsverwaltung/urlaubsverwaltung, pull requests merged in 2025-01, with the labels that each got.

#5053 db: adjust unique constraints to include tenant
  src/main/resources/dbchangelogs/changelog-5.11.0-adjust-unique-constraints.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: planned

#5042 Add 'RolesFromFullResourceAccess' claim mapper for launchpad to receive all permissions
  src/main/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromFullResourceAccessClaimMapper.java
  src/test/java/org/synyx/urlaubsverwaltung/security/oidc/RolesFromFullResourceAccessClaimMapperTest.java
Labels: status: planned

#5069 absence statistics: do not reduce half day on christmas eve and new y…
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendar.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarTest.java
Labels: status: planned

#5075 Absence statistic: Check if workingDays and workingDayInformation are not null
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendar.java
  src/test/java/org/synyx/urlaubsverwaltung/workingtime/WorkingTimeCalendarTest.java
Labels: type: bug, status: planned, topic: statistics

#5086 restore: handle personBaseData null value
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/restore/PersonRestoreService.java
Labels: status: planned

#5087 Fix incorrect date range on sick note csv export for all persons and allow csv export over the annual limit
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysStatisticsViewController.java
  src/main/resources/templates/sicknote/sick_days.html
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sickdays/SickDaysStatisticsViewControllerTest.java
Labels: status: planned

#5089 sick note: do not reduce half day on christmas eve and new years eve
  src/main/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNote.java
  src/test/java/org/synyx/urlaubsverwaltung/sicknote/sicknote/SickNoteTest.java
Labels: status: planned

#5099 Fix docker compose example with keycloak
  .examples/with-docker-compose/docker-compose.yaml
Labels: status: planned

#5103 Enhance the overtime reduction api for multi-day applications
  src/main/java/org/synyx/urlaubsverwaltung/absence/OvertimeAbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/OvertimeAbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/Application.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImpl.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/OvertimeAbsenceApiControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/ApplicationTest.java
Labels: status: planned

#5095 Enhance search results for people
  src/main/java/org/synyx/urlaubsverwaltung/person/PersonRepository.java
  src/main/java/org/synyx/urlaubsverwaltung/search/PageableSearchQuery.java
  src/test/java/org/synyx/urlaubsverwaltung/person/PersonRepositoryIT.java
  src/test/java/org/synyx/urlaubsverwaltung/search/PageableSearchQueryTest.java
Labels: status: planned

#5098 Fix calculation of used work days in overview for a application with …
  src/main/java/org/synyx/urlaubsverwaltung/overview/SickDaysOverview.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/UsedDaysOverview.java
  src/main/javascript/js/__tests__/send-get-days-request-for-turn-of-the-year.spec.js
  src/main/javascript/js/send-get-days-request-for-turn-of-the-year.js
  src/test/java/org/synyx/urlaubsverwaltung/overview/SickDaysOverviewTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/UsedDaysOverviewTest.java
Labels: status: planned

#5108 Upgrade ical4j to 3.2.19
  pom.xml
Labels: type: dependencies, status: planned, java

#5104 stabilize backup / restore mechanism for missing person values
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/ApplicationDataCollectionService.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/PersonHelper.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/backup/SickNoteDataCollectionService.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/model/OvertimeCommentDTO.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/restore/ApplicationRestoreService.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/restore/OvertimeRestoreService.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/backup/restore/SickNoteRestoreService.java
Labels: status: planned

#5109 make repubish events reusable
  src/main/java/org/synyx/urlaubsverwaltung/extension/application/ApplicationEventRepublisher.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/application/ApplicationEventRepublisherSingleTenant.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/sicknote/SickNoteEventRepublisher.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/sicknote/SickNoteEventRepublisherSingleTenant.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/vacationtype/VacationTypeEventRepublisher.java
  src/main/java/org/synyx/urlaubsverwaltung/extension/vacationtype/VacationTypeEventRepublisherSingleTenant.java
Labels: status: planned

#4752 Remove deprecated vacationdays method
  src/main/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImpl.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderService.java
  src/main/java/org/synyx/urlaubsverwaltung/account/VacationDaysService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/ApplicationForLeaveDetailsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/application/application/CalculationService.java
  src/main/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilder.java
  src/main/java/org/synyx/urlaubsverwaltung/dev/DemoDataPersonCreationForLocalDevelopment.java
  src/main/java/org/synyx/urlaubsverwaltung/overview/OverviewViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewController.java
  src/main/java/org/synyx/urlaubsverwaltung/util/DateUtil.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountInteractionServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/AccountServiceImplTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceIT.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysReminderServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/account/VacationDaysServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/application/CalculationServiceTest.java
  src/test/java/org/synyx/urlaubsverwaltung/application/statistics/ApplicationForLeaveStatisticsBuilderTest.java
  src/test/java/org/synyx/urlaubsverwaltung/overview/OverviewViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/person/web/PersonsViewControllerTest.java
  src/test/java/org/synyx/urlaubsverwaltung/util/DateUtilTest.java
Labels: type: enhancement, status: planned

#5118 ApplicationEventHandlerExtension: Fill translationKey for ProvidedVacationType
  src/main/java/org/synyx/urlaubsverwaltung/extension/application/ApplicationEventHandlerExtension.java
Labels: status: planned

#5120 Add liquibase script to add missing indices
  src/main/resources/dbchangelogs/changelog-5.15.0-add-missing-indices.xml
  src/main/resources/dbchangelogs/changelogmaster.xml
Labels: status: planned

#5122 bump node to 22.13.1
  .nvmrc
  .tool-versions
  pom.xml
Labels: type: dependencies, status: planned, javascript

#5121 Fix: Absence endpoint HATEOAS links
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiController.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsenceDto.java
  src/main/java/org/synyx/urlaubsverwaltung/absence/AbsencesDto.java
  src/test/java/org/synyx/urlaubsverwaltung/absence/AbsenceApiControllerIT.java
Labels: status: planned
